$(document).ready(function(){

  var pajaro = $(".fotopajaro")
  var titulos = $("#titulo")
  var instr = $("#instrucciones")

  pajaro.mouseenter(function(){
      $(this).css("fast", 1);
  });

  pajaro.mouseleave(function(){
    $(this).css("fast", 0.6); 
  });

  pajaro.click(function(){
    $(this).css("fast", 1);
    $(titulos).hide('fast');
    $(instr).hide('fast');
  });

  $("#fotocondor").click(function(){
    $("#condor").show('fast');
    $("#garza").hide('fast');
    $("#huala"). hide('fast');
    $("#aguila").hide('fast');
    $("#bandurria").hide('fast');
    $("#cormoran").hide('fast');
    $("#quetru").hide('fast');
    $("#caiquen").hide('fast');
    $("#caranca").hide('fast');
    $("#peuco").hide('fast');
    $("#tagua").hide('fast');
    $("#aguilucho").hide('fast');
    $("#patoreal").hide('fast');
    $("#tucuquere").hide('fast');
    $("#carpintero").hide('fast');
    $("#pilpilen").hide('fast');
    $("#martinpescador").hide('fast');
    $("#cortacorriente").hide('fast');
    $("#choroy").hide('fast');
    $("#torcaza").hide('fast');
    $("#concon").hide('fast');
    $("#cernicalo").hide('fast');
    $("#tordo").hide('fast');
    $("#huethuet").hide('fast');
    $("#diuca").hide('fast');
    $("#chincol").hide('fast');
    $("#rayadito").hide('fast');
    $("#chercan").hide('fast');
    $("#picaflor").hide('fast');
    $("#cachudito").hide('fast');
    

  });

  $("#fotogarzacuca").click(function(){
    $("#condor").hide('fast');
    $("#garza").show('fast');
    $("#huala"). hide('fast');
    $("#aguila").hide('fast');
    $("#bandurria").hide('fast');
    $("#cormoran").hide('fast');
    $("#quetru").hide('fast');
    $("#caiquen").hide('fast');
    $("#caranca").hide('fast');
    $("#peuco").hide('fast');
    $("#tagua").hide('fast');
    $("#aguilucho").hide('fast');
    $("#patoreal").hide('fast');
    $("#tucuquere").hide('fast');
    $("#carpintero").hide('fast');
    $("#pilpilen").hide('fast');
    $("#martinpescador").hide('fast');
    $("#cortacorriente").hide('fast');
    $("#choroy").hide('fast');
    $("#torcaza").hide('fast');
    $("#concon").hide('fast');
    $("#cernicalo").hide('fast');
    $("#tordo").hide('fast');
    $("#huethuet").hide('fast');
    $("#diuca").hide('fast');
    $("#chincol").hide('fast');
    $("#rayadito").hide('fast');
    $("#chercan").hide('fast');
    $("#picaflor").hide('fast');
    $("#cachudito").hide('fast');
    
  });

  $("#fotohuala").click(function(){
    $("#condor").hide('fast');
    $("#garza").hide('fast');
    $("#huala"). show('fast');
    $("#aguila").hide('fast');
    $("#bandurria").hide('fast');
    $("#cormoran").hide('fast');
    $("#quetru").hide('fast');
    $("#caiquen").hide('fast');
    $("#caranca").hide('fast');
    $("#peuco").hide('fast');
    $("#tagua").hide('fast');
    $("#aguilucho").hide('fast');
    $("#patoreal").hide('fast');
    $("#tucuquere").hide('fast');
    $("#carpintero").hide('fast');
    $("#pilpilen").hide('fast');
    $("#martinpescador").hide('fast');
    $("#cortacorriente").hide('fast');
    $("#choroy").hide('fast');
    $("#torcaza").hide('fast');
    $("#concon").hide('fast');
    $("#cernicalo").hide('fast');
    $("#tordo").hide('fast');
    $("#huethuet").hide('fast');
    $("#diuca").hide('fast');
    $("#chincol").hide('fast');
    $("#rayadito").hide('fast');
    $("#chercan").hide('fast');
    $("#picaflor").hide('fast');
    $("#cachudito").hide('fast');
    
  });

  $("#fotoaguila").click(function(){
    $("#condor").hide('fast');
    $("#garza").hide('fast');
    $("#huala"). hide('fast');
    $("#aguila").show('fast');
    $("#bandurria").hide('fast');
    $("#cormoran").hide('fast');
    $("#quetru").hide('fast');
    $("#caiquen").hide('fast');
    $("#caranca").hide('fast');
    $("#peuco").hide('fast');
    $("#tagua").hide('fast');
    $("#aguilucho").hide('fast');
    $("#patoreal").hide('fast');
    $("#tucuquere").hide('fast');
    $("#carpintero").hide('fast');
    $("#pilpilen").hide('fast');
    $("#martinpescador").hide('fast');
    $("#cortacorriente").hide('fast');
    $("#choroy").hide('fast');
    $("#torcaza").hide('fast');
    $("#concon").hide('fast');
    $("#cernicalo").hide('fast');
    $("#tordo").hide('fast');
    $("#huethuet").hide('fast');
    $("#diuca").hide('fast');
    $("#chincol").hide('fast');
    $("#rayadito").hide('fast');
    $("#chercan").hide('fast');
    $("#picaflor").hide('fast');
    $("#cachudito").hide('fast');
    
  });

  $("#fotobandurria").click(function(){
    $("#condor").hide('fast');
    $("#garza").hide('fast');
    $("#huala"). hide('fast');
    $("#aguila").hide('fast');
    $("#bandurria").show('fast');
    $("#cormoran").hide('fast');
    $("#quetru").hide('fast');
    $("#caiquen").hide('fast');
    $("#caranca").hide('fast');
    $("#peuco").hide('fast');
    $("#tagua").hide('fast');
    $("#aguilucho").hide('fast');
    $("#patoreal").hide('fast');
    $("#tucuquere").hide('fast');
    $("#carpintero").hide('fast');
    $("#pilpilen").hide('fast');
    $("#martinpescador").hide('fast');
    $("#cortacorriente").hide('fast');
    $("#choroy").hide('fast');
    $("#torcaza").hide('fast');
    $("#concon").hide('fast');
    $("#cernicalo").hide('fast');
    $("#tordo").hide('fast');
    $("#huethuet").hide('fast');
    $("#diuca").hide('fast');
    $("#chincol").hide('fast');
    $("#rayadito").hide('fast');
    $("#chercan").hide('fast');
    $("#picaflor").hide('fast');
    $("#cachudito").hide('fast');
    
  });

  $("#fotocormorandelasrocas").click(function(){
    $("#condor").hide('fast');
    $("#garza").hide('fast');
    $("#huala"). hide('fast');
    $("#aguila").hide('fast');
    $("#bandurria").hide('fast');
    $("#cormoran").show('fast');
    $("#quetru").hide('fast');
    $("#caiquen").hide('fast');
    $("#caranca").hide('fast');
    $("#peuco").hide('fast');
    $("#tagua").hide('fast');
    $("#aguilucho").hide('fast');
    $("#patoreal").hide('fast');
    $("#tucuquere").hide('fast');
    $("#carpintero").hide('fast');
    $("#pilpilen").hide('fast');
    $("#martinpescador").hide('fast');
    $("#cortacorriente").hide('fast');
    $("#choroy").hide('fast');
    $("#torcaza").hide('fast');
    $("#concon").hide('fast');
    $("#cernicalo").hide('fast');
    $("#tordo").hide('fast');
    $("#huethuet").hide('fast');
    $("#diuca").hide('fast');
    $("#chincol").hide('fast');
    $("#rayadito").hide('fast');
    $("#chercan").hide('fast');
    $("#picaflor").hide('fast');
    $("#cachudito").hide('fast');
    
  });

  $("#fotoquetruvolador").click(function(){
    $("#condor").hide('fast');
    $("#garza").hide('fast');
    $("#huala"). hide('fast');
    $("#aguila").hide('fast');
    $("#bandurria").hide('fast');
    $("#cormoran").hide('fast');
    $("#quetru").show('fast');
    $("#caiquen").hide('fast');
    $("#caranca").hide('fast');
    $("#peuco").hide('fast');
    $("#tagua").hide('fast');
    $("#aguilucho").hide('fast');
    $("#patoreal").hide('fast');
    $("#tucuquere").hide('fast');
    $("#carpintero").hide('fast');
    $("#pilpilen").hide('fast');
    $("#martinpescador").hide('fast');
    $("#cortacorriente").hide('fast');
    $("#choroy").hide('fast');
    $("#torcaza").hide('fast');
    $("#concon").hide('fast');
    $("#cernicalo").hide('fast');
    $("#tordo").hide('fast');
    $("#huethuet").hide('fast');
    $("#diuca").hide('fast');
    $("#chincol").hide('fast');
    $("#rayadito").hide('fast');
    $("#chercan").hide('fast');
    $("#picaflor").hide('fast');
    $("#cachudito").hide('fast');
    
  });

  $("#fotocaiquen").click(function(){
    $("#condor").hide('fast');
    $("#garza").hide('fast');
    $("#huala"). hide('fast');
    $("#aguila").hide('fast');
    $("#bandurria").hide('fast');
    $("#cormoran").hide('fast');
    $("#quetru").hide('fast');
    $("#caiquen").show('fast');
    $("#caranca").hide('fast');
    $("#peuco").hide('fast');
    $("#tagua").hide('fast');
    $("#aguilucho").hide('fast');
    $("#patoreal").hide('fast');
    $("#tucuquere").hide('fast');
    $("#carpintero").hide('fast');
    $("#pilpilen").hide('fast');
    $("#martinpescador").hide('fast');
    $("#cortacorriente").hide('fast');
    $("#choroy").hide('fast');
    $("#torcaza").hide('fast');
    $("#concon").hide('fast');
    $("#cernicalo").hide('fast');
    $("#tordo").hide('fast');
    $("#huethuet").hide('fast');
    $("#diuca").hide('fast');
    $("#chincol").hide('fast');
    $("#rayadito").hide('fast');
    $("#chercan").hide('fast');
    $("#picaflor").hide('fast');
    $("#cachudito").hide('fast');
    
  });

  $("#fotocaranca").click(function(){
    $("#condor").hide('fast');
    $("#garza").hide('fast');
    $("#huala"). hide('fast');
    $("#aguila").hide('fast');
    $("#bandurria").hide('fast');
    $("#cormoran").hide('fast');
    $("#quetru").hide('fast');
    $("#caiquen").hide('fast');
    $("#caranca").show('fast');
    $("#peuco").hide('fast');
    $("#tagua").hide('fast');
    $("#aguilucho").hide('fast');
    $("#patoreal").hide('fast');
    $("#tucuquere").hide('fast');
    $("#carpintero").hide('fast');
    $("#pilpilen").hide('fast');
    $("#martinpescador").hide('fast');
    $("#cortacorriente").hide('fast');
    $("#choroy").hide('fast');
    $("#torcaza").hide('fast');
    $("#concon").hide('fast');
    $("#cernicalo").hide('fast');
    $("#tordo").hide('fast');
    $("#huethuet").hide('fast');
    $("#diuca").hide('fast');
    $("#chincol").hide('fast');
    $("#rayadito").hide('fast');
    $("#chercan").hide('fast');
    $("#picaflor").hide('fast');
    $("#cachudito").hide('fast');
    
  });

  $("#fotopeuco").click(function(){
    $("#condor").hide('fast');
    $("#garza").hide('fast');
    $("#huala"). hide('fast');
    $("#aguila").hide('fast');
    $("#bandurria").hide('fast');
    $("#cormoran").hide('fast');
    $("#quetru").hide('fast');
    $("#caiquen").hide('fast');
    $("#caranca").hide('fast');
    $("#peuco").show('fast');
    $("#tagua").hide('fast');
    $("#aguilucho").hide('fast');
    $("#patoreal").hide('fast');
    $("#tucuquere").hide('fast');
    $("#carpintero").hide('fast');
    $("#pilpilen").hide('fast');
    $("#martinpescador").hide('fast');
    $("#cortacorriente").hide('fast');
    $("#choroy").hide('fast');
    $("#torcaza").hide('fast');
    $("#concon").hide('fast');
    $("#cernicalo").hide('fast');
    $("#tordo").hide('fast');
    $("#huethuet").hide('fast');
    $("#diuca").hide('fast');
    $("#chincol").hide('fast');
    $("#rayadito").hide('fast');
    $("#chercan").hide('fast');
    $("#picaflor").hide('fast');
    $("#cachudito").hide('fast');
    
  });

  $("#fototaguacomun").click(function(){
    $("#condor").hide('fast');
    $("#garza").hide('fast');
    $("#huala"). hide('fast');
    $("#aguila").hide('fast');
    $("#bandurria").hide('fast');
    $("#cormoran").hide('fast');
    $("#quetru").hide('fast');
    $("#caiquen").hide('fast');
    $("#caranca").hide('fast');
    $("#peuco").hide('fast');
    $("#tagua").show('fast');
    $("#aguilucho").hide('fast');
    $("#patoreal").hide('fast');
    $("#tucuquere").hide('fast');
    $("#carpintero").hide('fast');
    $("#pilpilen").hide('fast');
    $("#martinpescador").hide('fast');
    $("#cortacorriente").hide('fast');
    $("#choroy").hide('fast');
    $("#torcaza").hide('fast');
    $("#concon").hide('fast');
    $("#cernicalo").hide('fast');
    $("#tordo").hide('fast');
    $("#huethuet").hide('fast');
    $("#diuca").hide('fast');
    $("#chincol").hide('fast');
    $("#rayadito").hide('fast');
    $("#chercan").hide('fast');
    $("#picaflor").hide('fast');
    $("#cachudito").hide('fast');
    
  });

  $("#fotoaguilucho").click(function(){
    $("#condor").hide('fast');
    $("#garza").hide('fast');
    $("#huala"). hide('fast');
    $("#aguila").hide('fast');
    $("#bandurria").hide('fast');
    $("#cormoran").hide('fast');
    $("#quetru").hide('fast');
    $("#caiquen").hide('fast');
    $("#caranca").hide('fast');
    $("#peuco").hide('fast');
    $("#tagua").hide('fast');
    $("#aguilucho").show('fast');
    $("#patoreal").hide('fast');
    $("#tucuquere").hide('fast');
    $("#carpintero").hide('fast');
    $("#pilpilen").hide('fast');
    $("#martinpescador").hide('fast');
    $("#cortacorriente").hide('fast');
    $("#choroy").hide('fast');
    $("#torcaza").hide('fast');
    $("#concon").hide('fast');
    $("#cernicalo").hide('fast');
    $("#tordo").hide('fast');
    $("#huethuet").hide('fast');
    $("#diuca").hide('fast');
    $("#chincol").hide('fast');
    $("#rayadito").hide('fast');
    $("#chercan").hide('fast');
    $("#picaflor").hide('fast');
    $("#cachudito").hide('fast');
   
  });

  $("#fotopatoreal").click(function(){
    $("#condor").hide('fast');
    $("#garza").hide('fast');
    $("#huala"). hide('fast');
    $("#aguila").hide('fast');
    $("#bandurria").hide('fast');
    $("#cormoran").hide('fast');
    $("#quetru").hide('fast');
    $("#caiquen").hide('fast');
    $("#caranca").hide('fast');
    $("#peuco").hide('fast');
    $("#tagua").hide('fast');
    $("#aguilucho").hide('fast');
    $("#patoreal").show('fast');
    $("#tucuquere").hide('fast');
    $("#carpintero").hide('fast');
    $("#pilpilen").hide('fast');
    $("#martinpescador").hide('fast');
    $("#cortacorriente").hide('fast');
    $("#choroy").hide('fast');
    $("#torcaza").hide('fast');
    $("#concon").hide('fast');
    $("#cernicalo").hide('fast');
    $("#tordo").hide('fast');
    $("#huethuet").hide('fast');
    $("#diuca").hide('fast');
    $("#chincol").hide('fast');
    $("#rayadito").hide('fast');
    $("#chercan").hide('fast');
    $("#picaflor").hide('fast');
    $("#cachudito").hide('fast');
   
  });

  $("#fototucuquere").click(function(){
    $("#condor").hide('fast');
    $("#garza").hide('fast');
    $("#huala"). hide('fast');
    $("#aguila").hide('fast');
    $("#bandurria").hide('fast');
    $("#cormoran").hide('fast');
    $("#quetru").hide('fast');
    $("#caiquen").hide('fast');
    $("#caranca").hide('fast');
    $("#peuco").hide('fast');
    $("#tagua").hide('fast');
    $("#aguilucho").hide('fast');
    $("#patoreal").hide('fast');
    $("#tucuquere").show('fast');
    $("#carpintero").hide('fast');
    $("#pilpilen").hide('fast');
    $("#martinpescador").hide('fast');
    $("#cortacorriente").hide('fast');
    $("#choroy").hide('fast');
    $("#torcaza").hide('fast');
    $("#concon").hide('fast');
    $("#cernicalo").hide('fast');
    $("#tordo").hide('fast');
    $("#huethuet").hide('fast');
    $("#diuca").hide('fast');
    $("#chincol").hide('fast');
    $("#rayadito").hide('fast');
    $("#chercan").hide('fast');
    $("#picaflor").hide('fast');
    $("#cachudito").hide('fast');
   
  });

  $("#fotocarpinteronegro").click(function(){
    $("#condor").hide('fast');
    $("#garza").hide('fast');
    $("#huala"). hide('fast');
    $("#aguila").hide('fast');
    $("#bandurria").hide('fast');
    $("#cormoran").hide('fast');
    $("#quetru").hide('fast');
    $("#caiquen").hide('fast');
    $("#caranca").hide('fast');
    $("#peuco").hide('fast');
    $("#tagua").hide('fast');
    $("#aguilucho").hide('fast');
    $("#patoreal").hide('fast');
    $("#tucuquere").hide('fast');
    $("#carpintero").show('fast');
    $("#pilpilen").hide('fast');
    $("#martinpescador").hide('fast');
    $("#cortacorriente").hide('fast');
    $("#choroy").hide('fast');
    $("#torcaza").hide('fast');
    $("#concon").hide('fast');
    $("#cernicalo").hide('fast');
    $("#tordo").hide('fast');
    $("#huethuet").hide('fast');
    $("#diuca").hide('fast');
    $("#chincol").hide('fast');
    $("#rayadito").hide('fast');
    $("#chercan").hide('fast');
    $("#picaflor").hide('fast');
    $("#cachudito").hide('fast');
   
  });

  $("#fotopilpilenaustral").click(function(){
    $("#condor").hide('fast');
    $("#garza").hide('fast');
    $("#huala"). hide('fast');
    $("#aguila").hide('fast');
    $("#bandurria").hide('fast');
    $("#cormoran").hide('fast');
    $("#quetru").hide('fast');
    $("#caiquen").hide('fast');
    $("#caranca").hide('fast');
    $("#peuco").hide('fast');
    $("#tagua").hide('fast');
    $("#aguilucho").hide('fast');
    $("#patoreal").hide('fast');
    $("#tucuquere").hide('fast');
    $("#carpintero").hide('fast');
    $("#pilpilen").show('fast');
    $("#martinpescador").hide('fast');
    $("#cortacorriente").hide('fast');
    $("#choroy").hide('fast');
    $("#torcaza").hide('fast');
    $("#concon").hide('fast');
    $("#cernicalo").hide('fast');
    $("#tordo").hide('fast');
    $("#huethuet").hide('fast');
    $("#diuca").hide('fast');
    $("#chincol").hide('fast');
    $("#rayadito").hide('fast');
    $("#chercan").hide('fast');
    $("#picaflor").hide('fast');
    $("#cachudito").hide('fast');
   
  });

  $("#fotomartinpescador").click(function(){
    $("#condor").hide('fast');
    $("#garza").hide('fast');
    $("#huala"). hide('fast');
    $("#aguila").hide('fast');
    $("#bandurria").hide('fast');
    $("#cormoran").hide('fast');
    $("#quetru").hide('fast');
    $("#caiquen").hide('fast');
    $("#caranca").hide('fast');
    $("#peuco").hide('fast');
    $("#tagua").hide('fast');
    $("#aguilucho").hide('fast');
    $("#patoreal").hide('fast');
    $("#tucuquere").hide('fast');
    $("#carpintero").hide('fast');
    $("#pilpilen").hide('fast');
    $("#martinpescador").show('fast');
    $("#cortacorriente").hide('fast');
    $("#choroy").hide('fast');
    $("#torcaza").hide('fast');
    $("#concon").hide('fast');
    $("#cernicalo").hide('fast');
    $("#tordo").hide('fast');
    $("#huethuet").hide('fast');
    $("#diuca").hide('fast');
    $("#chincol").hide('fast');
    $("#rayadito").hide('fast');
    $("#chercan").hide('fast');
    $("#picaflor").hide('fast');
    $("#cachudito").hide('fast');
   
  });

  $("#fotopatocorrentino").click(function(){
    $("#condor").hide('fast');
    $("#garza").hide('fast');
    $("#huala"). hide('fast');
    $("#aguila").hide('fast');
    $("#bandurria").hide('fast');
    $("#cormoran").hide('fast');
    $("#quetru").hide('fast');
    $("#caiquen").hide('fast');
    $("#caranca").hide('fast');
    $("#peuco").hide('fast');
    $("#tagua").hide('fast');
    $("#aguilucho").hide('fast');
    $("#patoreal").hide('fast');
    $("#tucuquere").hide('fast');
    $("#carpintero").hide('fast');
    $("#pilpilen").hide('fast');
    $("#martinpescador").hide('fast');
    $("#cortacorriente").show('fast');
    $("#choroy").hide('fast');
    $("#torcaza").hide('fast');
    $("#concon").hide('fast');
    $("#cernicalo").hide('fast');
    $("#tordo").hide('fast');
    $("#huethuet").hide('fast');
    $("#diuca").hide('fast');
    $("#chincol").hide('fast');
    $("#rayadito").hide('fast');
    $("#chercan").hide('fast');
    $("#picaflor").hide('fast');
    $("#cachudito").hide('fast');
   
  });

  $("#fotochoroy").click(function(){
    $("#condor").hide('fast');
    $("#garza").hide('fast');
    $("#huala"). hide('fast');
    $("#aguila").hide('fast');
    $("#bandurria").hide('fast');
    $("#cormoran").hide('fast');
    $("#quetru").hide('fast');
    $("#caiquen").hide('fast');
    $("#caranca").hide('fast');
    $("#peuco").hide('fast');
    $("#tagua").hide('fast');
    $("#aguilucho").hide('fast');
    $("#patoreal").hide('fast');
    $("#tucuquere").hide('fast');
    $("#carpintero").hide('fast');
    $("#pilpilen").hide('fast');
    $("#martinpescador").hide('fast');
    $("#cortacorriente").hide('fast');
    $("#choroy").show('fast');
    $("#torcaza").hide('fast');
    $("#concon").hide('fast');
    $("#cernicalo").hide('fast');
    $("#tordo").hide('fast');
    $("#huethuet").hide('fast');
    $("#diuca").hide('fast');
    $("#chincol").hide('fast');
    $("#rayadito").hide('fast');
    $("#chercan").hide('fast');
    $("#picaflor").hide('fast');
    $("#cachudito").hide('fast');
   
  });

  $("#fototorcaza").click(function(){
    $("#condor").hide('fast');
    $("#garza").hide('fast');
    $("#huala"). hide('fast');
    $("#aguila").hide('fast');
    $("#bandurria").hide('fast');
    $("#cormoran").hide('fast');
    $("#quetru").hide('fast');
    $("#caiquen").hide('fast');
    $("#caranca").hide('fast');
    $("#peuco").hide('fast');
    $("#tagua").hide('fast');
    $("#aguilucho").hide('fast');
    $("#patoreal").hide('fast');
    $("#tucuquere").hide('fast');
    $("#carpintero").hide('fast');
    $("#pilpilen").hide('fast');
    $("#martinpescador").hide('fast');
    $("#cortacorriente").hide('fast');
    $("#choroy").hide('fast');
    $("#torcaza").show('fast');
    $("#concon").hide('fast');
    $("#cernicalo").hide('fast');
    $("#tordo").hide('fast');
    $("#huethuet").hide('fast');
    $("#diuca").hide('fast');
    $("#chincol").hide('fast');
    $("#rayadito").hide('fast');
    $("#chercan").hide('fast');
    $("#picaflor").hide('fast');
    $("#cachudito").hide('fast');
   
  });

  $("#fotoconcondechiloe").click(function(){
    $("#condor").hide('fast');
    $("#garza").hide('fast');
    $("#huala"). hide('fast');
    $("#aguila").hide('fast');
    $("#bandurria").hide('fast');
    $("#cormoran").hide('fast');
    $("#quetru").hide('fast');
    $("#caiquen").hide('fast');
    $("#caranca").hide('fast');
    $("#peuco").hide('fast');
    $("#tagua").hide('fast');
    $("#aguilucho").hide('fast');
    $("#patoreal").hide('fast');
    $("#tucuquere").hide('fast');
    $("#carpintero").hide('fast');
    $("#pilpilen").hide('fast');
    $("#martinpescador").hide('fast');
    $("#cortacorriente").hide('fast');
    $("#choroy").hide('fast');
    $("#torcaza").hide('fast');
    $("#concon").show('fast');
    $("#cernicalo").hide('fast');
    $("#tordo").hide('fast');
    $("#huethuet").hide('fast');
    $("#diuca").hide('fast');
    $("#chincol").hide('fast');
    $("#rayadito").hide('fast');
    $("#chercan").hide('fast');
    $("#picaflor").hide('fast');
    $("#cachudito").hide('fast');
   
  });

  $("#fotocernicalo").click(function(){
    $("#condor").hide('fast');
    $("#garza").hide('fast');
    $("#huala"). hide('fast');
    $("#aguila").hide('fast');
    $("#bandurria").hide('fast');
    $("#cormoran").hide('fast');
    $("#quetru").hide('fast');
    $("#caiquen").hide('fast');
    $("#caranca").hide('fast');
    $("#peuco").hide('fast');
    $("#tagua").hide('fast');
    $("#aguilucho").hide('fast');
    $("#patoreal").hide('fast');
    $("#tucuquere").hide('fast');
    $("#carpintero").hide('fast');
    $("#pilpilen").hide('fast');
    $("#martinpescador").hide('fast');
    $("#cortacorriente").hide('fast');
    $("#choroy").hide('fast');
    $("#torcaza").hide('fast');
    $("#concon").hide('fast');
    $("#cernicalo").show('fast');
    $("#tordo").hide('fast');
    $("#huethuet").hide('fast');
    $("#diuca").hide('fast');
    $("#chincol").hide('fast');
    $("#rayadito").hide('fast');
    $("#chercan").hide('fast');
    $("#picaflor").hide('fast');
    $("#cachudito").hide('fast');
   
  });

  $("#fototordo").click(function(){
    $("#condor").hide('fast');
    $("#garza").hide('fast');
    $("#huala"). hide('fast');
    $("#aguila").hide('fast');
    $("#bandurria").hide('fast');
    $("#cormoran").hide('fast');
    $("#quetru").hide('fast');
    $("#caiquen").hide('fast');
    $("#caranca").hide('fast');
    $("#peuco").hide('fast');
    $("#tagua").hide('fast');
    $("#aguilucho").hide('fast');
    $("#patoreal").hide('fast');
    $("#tucuquere").hide('fast');
    $("#carpintero").hide('fast');
    $("#pilpilen").hide('fast');
    $("#martinpescador").hide('fast');
    $("#cortacorriente").hide('fast');
    $("#choroy").hide('fast');
    $("#torcaza").hide('fast');
    $("#concon").hide('fast');
    $("#cernicalo").hide('fast');
    $("#tordo").show('fast');
    $("#huethuet").hide('fast');
    $("#diuca").hide('fast');
    $("#chincol").hide('fast');
    $("#rayadito").hide('fast');
    $("#chercan").hide('fast');
    $("#picaflor").hide('fast');
    $("#cachudito").hide('fast');
   
  });

  $("#fotohuethuet").click(function(){
    $("#condor").hide('fast');
    $("#garza").hide('fast');
    $("#huala"). hide('fast');
    $("#aguila").hide('fast');
    $("#bandurria").hide('fast');
    $("#cormoran").hide('fast');
    $("#quetru").hide('fast');
    $("#caiquen").hide('fast');
    $("#caranca").hide('fast');
    $("#peuco").hide('fast');
    $("#tagua").hide('fast');
    $("#aguilucho").hide('fast');
    $("#patoreal").hide('fast');
    $("#tucuquere").hide('fast');
    $("#carpintero").hide('fast');
    $("#pilpilen").hide('fast');
    $("#martinpescador").hide('fast');
    $("#cortacorriente").hide('fast');
    $("#choroy").hide('fast');
    $("#torcaza").hide('fast');
    $("#concon").hide('fast');
    $("#cernicalo").hide('fast');
    $("#tordo").hide('fast');
    $("#huethuet").show('fast');
    $("#diuca").hide('fast');
    $("#chincol").hide('fast');
    $("#rayadito").hide('fast');
    $("#chercan").hide('fast');
    $("#picaflor").hide('fast');
    $("#cachudito").hide('fast');
   
  });

  $("#fotodiucadechiloe").click(function(){
    $("#condor").hide('fast');
    $("#garza").hide('fast');
    $("#huala"). hide('fast');
    $("#aguila").hide('fast');
    $("#bandurria").hide('fast');
    $("#cormoran").hide('fast');
    $("#quetru").hide('fast');
    $("#caiquen").hide('fast');
    $("#caranca").hide('fast');
    $("#peuco").hide('fast');
    $("#tagua").hide('fast');
    $("#aguilucho").hide('fast');
    $("#patoreal").hide('fast');
    $("#tucuquere").hide('fast');
    $("#carpintero").hide('fast');
    $("#pilpilen").hide('fast');
    $("#martinpescador").hide('fast');
    $("#cortacorriente").hide('fast');
    $("#choroy").hide('fast');
    $("#torcaza").hide('fast');
    $("#concon").hide('fast');
    $("#cernicalo").hide('fast');
    $("#tordo").hide('fast');
    $("#huethuet").hide('fast');
    $("#diuca").show('fast');
    $("#chincol").hide('fast');
    $("#rayadito").hide('fast');
    $("#chercan").hide('fast');
    $("#picaflor").hide('fast');
    $("#cachudito").hide('fast');
   
  });

  $("#fotochincol").click(function(){
    $("#condor").hide('fast');
    $("#garza").hide('fast');
    $("#huala"). hide('fast');
    $("#aguila").hide('fast');
    $("#bandurria").hide('fast');
    $("#cormoran").hide('fast');
    $("#quetru").hide('fast');
    $("#caiquen").hide('fast');
    $("#caranca").hide('fast');
    $("#peuco").hide('fast');
    $("#tagua").hide('fast');
    $("#aguilucho").hide('fast');
    $("#patoreal").hide('fast');
    $("#tucuquere").hide('fast');
    $("#carpintero").hide('fast');
    $("#pilpilen").hide('fast');
    $("#martinpescador").hide('fast');
    $("#cortacorriente").hide('fast');
    $("#choroy").hide('fast');
    $("#torcaza").hide('fast');
    $("#concon").hide('fast');
    $("#cernicalo").hide('fast');
    $("#tordo").hide('fast');
    $("#huethuet").hide('fast');
    $("#diuca").hide('fast');
    $("#chincol").show('fast');
    $("#rayadito").hide('fast');
    $("#chercan").hide('fast');
    $("#picaflor").hide('fast');
    $("#cachudito").hide('fast');
   
  });

  $("#fotorayaditodechiloe").click(function(){
    $("#condor").hide('fast');
    $("#garza").hide('fast');
    $("#huala"). hide('fast');
    $("#aguila").hide('fast');
    $("#bandurria").hide('fast');
    $("#cormoran").hide('fast');
    $("#quetru").hide('fast');
    $("#caiquen").hide('fast');
    $("#caranca").hide('fast');
    $("#peuco").hide('fast');
    $("#tagua").hide('fast');
    $("#aguilucho").hide('fast');
    $("#patoreal").hide('fast');
    $("#tucuquere").hide('fast');
    $("#carpintero").hide('fast');
    $("#pilpilen").hide('fast');
    $("#martinpescador").hide('fast');
    $("#cortacorriente").hide('fast');
    $("#choroy").hide('fast');
    $("#torcaza").hide('fast');
    $("#concon").hide('fast');
    $("#cernicalo").hide('fast');
    $("#tordo").hide('fast');
    $("#huethuet").hide('fast');
    $("#diuca").hide('fast');
    $("#chincol").hide('fast');
    $("#rayadito").show('fast');
    $("#chercan").hide('fast');
    $("#picaflor").hide('fast');
    $("#cachudito").hide('fast');
   
  });

  $("#fotochercan").click(function(){
    $("#condor").hide('fast');
    $("#garza").hide('fast');
    $("#huala"). hide('fast');
    $("#aguila").hide('fast');
    $("#bandurria").hide('fast');
    $("#cormoran").hide('fast');
    $("#quetru").hide('fast');
    $("#caiquen").hide('fast');
    $("#caranca").hide('fast');
    $("#peuco").hide('fast');
    $("#tagua").hide('fast');
    $("#aguilucho").hide('fast');
    $("#patoreal").hide('fast');
    $("#tucuquere").hide('fast');
    $("#carpintero").hide('fast');
    $("#pilpilen").hide('fast');
    $("#martinpescador").hide('fast');
    $("#cortacorriente").hide('fast');
    $("#choroy").hide('fast');
    $("#torcaza").hide('fast');
    $("#concon").hide('fast');
    $("#cernicalo").hide('fast');
    $("#tordo").hide('fast');
    $("#huethuet").hide('fast');
    $("#diuca").hide('fast');
    $("#chincol").hide('fast');
    $("#rayadito").hide('fast');
    $("#chercan").show('fast');
    $("#picaflor").hide('fast');
    $("#cachudito").hide('fast');
   
  });

  $("#fotopicaflorchico").click(function(){
    $("#condor").hide('fast');
    $("#garza").hide('fast');
    $("#huala"). hide('fast');
    $("#aguila").hide('fast');
    $("#bandurria").hide('fast');
    $("#cormoran").hide('fast');
    $("#quetru").hide('fast');
    $("#caiquen").hide('fast');
    $("#caranca").hide('fast');
    $("#peuco").hide('fast');
    $("#tagua").hide('fast');
    $("#aguilucho").hide('fast');
    $("#patoreal").hide('fast');
    $("#tucuquere").hide('fast');
    $("#carpintero").hide('fast');
    $("#pilpilen").hide('fast');
    $("#martinpescador").hide('fast');
    $("#cortacorriente").hide('fast');
    $("#choroy").hide('fast');
    $("#torcaza").hide('fast');
    $("#concon").hide('fast');
    $("#cernicalo").hide('fast');
    $("#tordo").hide('fast');
    $("#huethuet").hide('fast');
    $("#diuca").hide('fast');
    $("#chincol").hide('fast');
    $("#rayadito").hide('fast');
    $("#chercan").hide('fast');
    $("#picaflor").show('fast');
    $("#cachudito").hide('fast');
   
  });

  $("#fotocachudito").click(function(){
    $("#condor").hide('fast');
    $("#garza").hide('fast');
    $("#huala"). hide('fast');
    $("#aguila").hide('fast');
    $("#bandurria").hide('fast');
    $("#cormoran").hide('fast');
    $("#quetru").hide('fast');
    $("#caiquen").hide('fast');
    $("#caranca").hide('fast');
    $("#peuco").hide('fast');
    $("#tagua").hide('fast');
    $("#aguilucho").hide('fast');
    $("#patoreal").hide('fast');
    $("#tucuquere").hide('fast');
    $("#carpintero").hide('fast');
    $("#pilpilen").hide('fast');
    $("#martinpescador").hide('fast');
    $("#cortacorriente").hide('fast');
    $("#choroy").hide('fast');
    $("#torcaza").hide('fast');
    $("#concon").hide('fast');
    $("#cernicalo").hide('fast');
    $("#tordo").hide('fast');
    $("#huethuet").hide('fast');
    $("#diuca").hide('fast');
    $("#chincol").hide('fast');
    $("#rayadito").hide('fast');
    $("#chercan").hide('fast');
    $("#picaflor").hide('fast');
    $("#cachudito").show('fast');
   
  });

  $("#fotocondor").click(function(){
    $("#condor").show('fast');
    $("#garza").hide('fast');
    $("#huala"). hide('fast');
    $("#aguila").hide('fast');
    $("#bandurria").hide('fast');
    $("#cormoran").hide('fast');
    $("#quetru").hide('fast');
    $("#caiquen").hide('fast');
    $("#caranca").hide('fast');
    $("#peuco").hide('fast');
    $("#tagua").hide('fast');
    $("#aguilucho").hide('fast');
    $("#patoreal").hide('fast');
    $("#tucuquere").hide('fast');
    $("#carpintero").hide('fast');
    $("#pilpilen").hide('fast');
    $("#martinpescador").hide('fast');
    $("#cortacorriente").hide('fast');
    $("#choroy").hide('fast');
    $("#torcaza").hide('fast');
    $("#concon").hide('fast');
    $("#cernicalo").hide('fast');
    $("#tordo").hide('fast');
    $("#huethuet").hide('fast');
    $("#diuca").hide('fast');
    $("#chincol").hide('fast');
    $("#rayadito").hide('fast');
    $("#chercan").hide('fast');
    $("#picaflor").hide('fast');
    $("#cachudito").hide('fast');
   
  });

  $("#fotocondor").click(function(){
    $("#condor").show('fast');
    $("#garza").hide('fast');
    $("#huala"). hide('fast');
    $("#aguila").hide('fast');
    $("#bandurria").hide('fast');
    $("#cormoran").hide('fast');
    $("#quetru").hide('fast');
    $("#caiquen").hide('fast');
    $("#caranca").hide('fast');
    $("#peuco").hide('fast');
    $("#tagua").hide('fast');
    $("#aguilucho").hide('fast');
    $("#patoreal").hide('fast');
    $("#tucuquere").hide('fast');
    $("#carpintero").hide('fast');
    $("#pilpilen").hide('fast');
    $("#martinpescador").hide('fast');
    $("#cortacorriente").hide('fast');
    $("#choroy").hide('fast');
    $("#torcaza").hide('fast');
    $("#concon").hide('fast');
    $("#cernicalo").hide('fast');
    $("#tordo").hide('fast');
    $("#huethuet").hide('fast');
    $("#diuca").hide('fast');
    $("#chincol").hide('fast');
    $("#rayadito").hide('fast');
    $("#chercan").hide('fast');
    $("#picaflor").hide('fast');
    $("#cachudito").hide('fast');
   
  });

  $("#fotocondor").click(function(){
    $("#condor").show('fast');
    $("#garza").hide('fast');
    $("#huala"). hide('fast');
    $("#aguila").hide('fast');
    $("#bandurria").hide('fast');
    $("#cormoran").hide('fast');
    $("#quetru").hide('fast');
    $("#caiquen").hide('fast');
    $("#caranca").hide('fast');
    $("#peuco").hide('fast');
    $("#tagua").hide('fast');
    $("#aguilucho").hide('fast');
    $("#patoreal").hide('fast');
    $("#tucuquere").hide('fast');
    $("#carpintero").hide('fast');
    $("#pilpilen").hide('fast');
    $("#martinpescador").hide('fast');
    $("#cortacorriente").hide('fast');
    $("#choroy").hide('fast');
    $("#torcaza").hide('fast');
    $("#concon").hide('fast');
    $("#cernicalo").hide('fast');
    $("#tordo").hide('fast');
    $("#huethuet").hide('fast');
    $("#diuca").hide('fast');
    $("#chincol").hide('fast');
    $("#rayadito").hide('fast');
    $("#chercan").hide('fast');
    $("#picaflor").hide('fast');
    $("#cachudito").hide('fast');
  });
  
  $("#div1").css("opacity", ".5");


  $(".circulolagunadellaja").hover(function(){
    $("#fotocondor").css("opacity", "1");
    $("#fotogarzacuca").css("opacity", "0.2");
    $("#fotohuala").css("opacity", "0.2");
    $("fotoaguila").css("opacity", "1");
    $("fotobandurria").css("opacity", "1");
    $("#fotocormorandelasrocas").css("opacity", "0.2");
    $("#fotoquetruvolador").css("opacity", "0.2");
    $("#fotocaiquen").css("opacity", "0.2");
    $("#fotocaranca").css("opacity", "0.2");
    $("#fotopeuco").css("opacity", "1");
    $("#fototaguacomun").css("opacity", "1");
    $("#fotoaguilucho").css("opacity", "1");
    $("#fotopatoreal").css("opacity", "0.2");  
    $("#fototucuquere").css("opacity", "1");
    $("#fotocarpinteronegro").css("opacity", "1");
    $("#fotopilpilenaustral").css("opacity", "0.2");
    $("#fotomartinpescador").css("opacity", "0.2");
    $("#fotopatocorrentino").css("opacity", "1");
    $("#fotochoroy").css("opacity", "0.2");
    $("#fototorcaza").css("opacity", "0.2");
    $("#fotoconcondechiloe").css("opacity", "0.2");
    $("#fotocernicalo").css("opacity", "1");
    $("#fototordo").css("opacity", "1");
    $("#fotohuethuet").css("opacity", "1");
    $("#fotodiucadechiloe").css("opacity", "0.2");
    $("#fotochincol").css("opacity", "1");
    $("#fotorayaditodechiloe").css("opacity", "1");
    $("#fotochercan").css("opacity","1");
    $("#fotopicaflorchico").css("opacity", "1");
    $("#fotocachudito").css("opacity", "1");
  });

  $("#circulononguen").click(function(){
    $("#fotocachudito").css("fast",0.2);
    $("#fotopicaflorchico").css("fast",0.2);
    $("#fotochercan").css("fast",0.2);
    $("#fotochincol").css("fast",0.2);
    $("#fotodiucadechiloe").css("fast",0.2);
    $("#fotohuethuet").css("fast",0.2);
    $("#fototordo").css("fast",0.2);
    $("#fotocernicalo").css("fast",0.2);
    $("#fotoconcondechiloe").css("fast",0.2);
    $("#fototorcaza").css("fast",0.2);
    $("#fotochoroy").css("fast",0.2);
    $("#fotopatocorrentino").css("fast",0.2);
    $("#fotomartinpescador").css("fast",0.2);
    $("#fotopilpilenaustral").css("fast",0.2);
    $("#fotocarpinteronegro").css("fast",0.2);
    $("#fototucuquere").css("fast",0.2);
    $("#fotopatoreal").css("fast",0.2);
    $("#fotopeuco").css("fast",0.2);
    $("#fotocaranca").css("fast",0.2);
    $("#fotocaiquen").css("fast",0.2);
    $("#fotoquetruvolador").css("fast",0.2);
    $("#fotocormorandelasrocas").css("fast",0.2);
    $("#fotobandurria").css("fast",0.2);
    $("#fotoaguila").css("fast",0.2);
    $("#fotogarzacuca").css("fast",0.2);
    $("#fotocondor").css("fast",0.2);
  });

  $("#circulohuerquehue").click(function(){
    $("#fotocachudito").css("fast",0.2);
    $("#fotopicaflorchico").css("fast",0.2);
    $("#fotochercan").css("fast",0.2);
    $("#fotochincol").css("fast",0.2);
    $("#fotodiucadechiloe").css("fast",0.2);
    $("#fotohuethuet").css("fast",0.2);
    $("#fototordo").css("fast",0.2);
    $("#fotocernicalo").css("fast",0.2);
    $("#fotoconcondechiloe").css("fast",0.2);
    $("#fotopatocorrentino").css("fast",0.2);
    $("#fotomartinpescador").css("fast",0.2);
    $("#fotopilpilenaustral").css("fast",0.2);
    $("#fototucuquere").css("fast",0.2);
    $("#fotopatoreal").css("fast",0.2);
    $("#fotopeuco").css("fast",0.2);
    $("#fotocaranca").css("fast",0.2);
    $("#fotocaiquen").css("fast",0.2);
    $("#fotocormorandelasrocas").css("fast",0.2);
    $("#fotobandurria").css("fast",0.2);
    $("#fotoaguila").css("fast",0.2);
    $("#fotogarzacuca").css("fast",0.2);
  });

  $("#circulovillarrica").click(function(){
    $("#fotocachudito").css("fast",0.2);
    $("#fotopicaflorchico").css("fast",0.2);
    $("#fotochincol").css("fast",0.2);
    $("#fotodiucadechiloe").css("fast",0.2);
    $("#fotohuethuet").css("fast",0.2);
    $("#fototordo").css("fast",0.2);
    $("#fotocernicalo").css("fast",0.2);
    $("#fotoconcondechiloe").css("fast",0.2);
    $("#fototorcaza").css("fast",0.2);
    $("#fotochoroy").css("fast",0.2);
    $("#fotopatocorrentino").css("fast",0.2);
    $("#fotomartinpescador").css("fast",0.2);
    $("#fotopilpilenaustral").css("fast",0.2);
    $("#fotocarpinteronegro").css("fast",0.2);
    $("#fototucuquere").css("fast",0.2);
    $("#fotocaranca").css("fast",0.2);
    $("#fotocaiquen").css("fast",0.2);
    $("#fotoquetruvolador").css("fast",0.2);
    $("#fotocormorandelasrocas").css("fast",0.2);
    $("#fotobandurria").css("fast",0.2);
    $("#fotogarzacuca").css("fast",0.2);
    $("#fotocondor").css("fast",0.2);
  });

  $("#circulonahuelbuta").click(function(){
    $("#fotochincol").css("fast",0.2);
    $("#fotodiucadechiloe").css("fast",0.2);
    $("#fototordo").css("fast",0.2);
    $("#fotoconcondechiloe").css("fast",0.2);
    $("#fototorcaza").css("fast",0.2);
    $("#fotochoroy").css("fast",0.2);
    $("#fotopatocorrentino").css("fast",0.2);
    $("#fotomartinpescador").css("fast",0.2);
    $("#fotopilpilenaustral").css("fast",0.2);
    $("#fotocaranca").css("fast",0.2);
    $("#fotocaiquen").css("fast",0.2);
    $("#fotoquetruvolador").css("fast",0.2);
    $("#fotocormorandelasrocas").css("fast",0.2);
    $("#fotohuala").css("fast",0.2);
    $("#fotogarzacuca").css("fast",0.2);
    $("#fotocondor").css("fast",0.2);
  });
  $("#circulotolhuaca").click(function(){
    $("#fotocachudito").css("fast",0.2);
    $("#fotopicaflorchico").css("fast",0.2);
    $("#fotochercan").css("fast",0.2);
    $("#fotorayaditodechiloe").css("fast",0.2);
    $("#fotochincol").css("fast",0.2);
    $("#fotodiucadechiloe").css("fast",0.2);
    $("#fotohuethuet").css("fast",0.2);
    $("#fototordo").css("fast",0.2);
    $("#fotocernicalo").css("fast",0.2);
    $("#fotoconcondechiloe").css("fast",0.2);
    $("#fotopatocorrentino").css("fast",0.2);
    $("#fotopilpilenaustral").css("fast",0.2);
    $("#fototucuquere").css("fast",0.2);
    $("#fotopatoreal").css("fast",0.2);
    $("#fotopeuco").css("fast",0.2);
    $("#fotocaranca").css("fast",0.2);
    $("#fotocaiquen").css("fast",0.2);
    $("#fotoquetruvolador").css("fast",0.2);
    $("#fotocormorandelasrocas").css("fast",0.2);
    $("#fotohuala").css("fast",0.2);
    $("#fotogarzacuca").css("fast",0.2);
  });

  $("#circuloconguillio").click(function(){
    $("#fotodiucadechiloe").css("fast",0.2);
    $("#fotoconcondechiloe").css("fast",0.2);
    $("#fototorcaza").css("fast",0.2);
    $("#fotopilpilenaustral").css("fast",0.2);
    $("#fotoaguilucho").css("fast",0.2);
    $("#fotocaranca").css("fast",0.2);
    $("#fotocaiquen").css("fast",0.2);
    $("#fotocormorandelasrocas").css("fast",0.2);
    $("#fotobandurria").css("fast",0.2);
    $("#fotoaguila").css("fast",0.2);
  });

  $("#circuloalercecostero").click(function(){
    $("#fotorayaditodechiloe").css("fast",0.2);
    $("#fotopicaflorchico").css("fast",0.2);
    $("#fotochercan").css("fast",0.2);
    $("#fotochincol").css("fast",0.2);
    $("#fotodiucadechiloe").css("fast",0.2);
    $("#fototordo").css("fast",0.2);
    $("#fotocernicalo").css("fast",0.2);
    $("#fotoconcondechiloe").css("fast",0.2);
    $("#fototorcaza").css("fast",0.2);
    $("#fotochoroy").css("fast",0.2);
    $("#fotopatocorrentino").css("fast",0.2);
    $("#fotopilpilenaustral").css("fast",0.2);
    $("#fototucuquere").css("fast",0.2);
    $("#fotoaguilucho").css("fast",0.2);
    $("#fototaguacomun").css("fast",0.2);
    $("#fotocaranca").css("fast",0.2);
    $("#fotoquetruvolador").css("fast",0.2);
    $("#fotocormorandelasrocas").css("fast",0.2);
    $("#fotobandurria").css("fast",0.2);
    $("#fotoaguila").css("fast",0.2);
    $("#fotohuala").css("fast",0.2);
    $("#fotogarzacuca").css("fast",0.2);
    $("#fotocondor").css("fast",0.2);
  });


  $("#circulopumalin").click(function(){
    $("#fotocachudito").css("fast",0.2);
    $("#fotochercan").css("fast",0.2);
    $("#fotochincol").css("fast",0.2);
    $("#fotorayaditodechiloe").css("fast",0.2);
    $("#fotohuethuet").css("fast",0.2);
    $("#fototordo").css("fast",0.2);
    $("#fotocernicalo").css("fast",0.2);
    $("#fotoconcondechiloe").css("fast",0.2);
    $("#fototorcaza").css("fast",0.2);
    $("#fotochoroy").css("fast",0.2);
    $("#fotopatocorrentino").css("fast",0.2);
    $("#fotomartinpescador").css("fast",0.2);
    $("#fotopilpilenaustral").css("fast",0.2);
    $("#fototucuquere").css("fast",0.2);
    $("#fotopatoreal").css("fast",0.2);
    $("#fototaguacomun").css("fast",0.2);
    $("#fotocaranca").css("fast",0.2);
    $("#fotocaiquen").css("fast",0.2);
    $("#fotoquetruvolador").css("fast",0.2);
    $("#fotocormorandelasrocas").css("fast",0.2);
    $("#fotohuala").css("fast",0.2);
    $("#fotoaguila").css("fast",0.2);
    $("#fotogarzacuca").css("fast",0.2);
  });


  $("#circulopuyehue").click(function(){
    $("#fotocachudito").css("fast",0.2);
    $("#fotopicaflorchico").css("fast",0.2);
    $("#fotorayaditodechiloe").css("fast",0.2);
    $("#fotochincol").css("fast",0.2);
    $("#fotodiucadechiloe").css("fast",0.2);
    $("#fototordo").css("fast",0.2);
    $("#fotocernicalo").css("fast",0.2);
    $("#fotoconcondechiloe").css("fast",0.2);
    $("#fotomartinpescador").css("fast",0.2);
    $("#fotopilpilenaustral").css("fast",0.2);
    $("#fotocarpinteronegro").css("fast",0.2);
    $("#fototucuquere").css("fast",0.2);
    $("#fotopatoreal").css("fast",0.2);
    $("#fototaguacomun").css("fast",0.2);
    $("#fotopeuco").css("fast",0.2);
    $("#fotocaranca").css("fast",0.2);
    $("#fotocaiquen").css("fast",0.2);
    $("#fotoquetruvolador").css("fast",0.2);
    $("#fotocormorandelasrocas").css("fast",0.2);
    $("#fotoaguila").css("fast",0.2);
    $("#fotogarzacuca").css("fast",0.2);
  });



  $("#circulovicenteperezrosales").click(function(){
    $("#fotocachudito").css("fast",0.2);
    $("#fotochercan").css("fast",0.2);
    $("#fotochincol").css("fast",0.2);
    $("#fotodiucadechiloe").css("fast",0.2);
    $("#fotohuethuet").css("fast",0.2);
    $("#fototordo").css("fast",0.2);
    $("#fotocernicalo").css("fast",0.2);
    $("#fotoconcondechiloe").css("fast",0.2);
    $("#fototorcaza").css("fast",0.2);
    $("#fotochoroy").css("fast",0.2);
    $("#fotomartinpescador").css("fast",0.2);
    $("#fotopilpilenaustral").css("fast",0.2);
    $("#fototucuquere").css("fast",0.2);
    $("#fotopatoreal").css("fast",0.2);
    $("#fotopeuco").css("fast",0.2);
    $("#fotohuala").css("fast",0.2);
    $("#fotocaranca").css("fast",0.2);
    $("#fotocaiquen").css("fast",0.2);
    $("#fotoquetruvolador").css("fast",0.2);
    $("#fotocormorandelasrocas").css("fast",0.2);
    $("#fotobandurria").css("fast",0.2);
    $("#fotoaguilucho").css("fast",0.2);
    $("#fotogarzacuca").css("fast",0.2);
    $("#fotocondor").css("fast",0.2);
  });


  $("#circulocorcovado").click(function(){
    $("#fotocachudito").css("fast",0.2);
    $("#fotopicaflorchico").css("fast",0.2);
    $("#fotochercan").css("fast",0.2);
    $("#fotochincol").css("fast",0.2);
    $("#fotodiucadechiloe").css("fast",0.2);
    $("#fotorayaditodechiloe").css("fast",0.2);
    $("#fotohuethuet").css("fast",0.2);
    $("#fototordo").css("fast",0.2);
    $("#fotocernicalo").css("fast",0.2);
    $("#fotoconcondechiloe").css("fast",0.2);
    $("#fototorcaza").css("fast",0.2);
    $("#fotochoroy").css("fast",0.2);
    $("#fotopatocorrentino").css("fast",0.2);
    $("#fotomartinpescador").css("fast",0.2);
    $("#fotopilpilenaustral").css("fast",0.2);
    $("#fotoaguilucho").css("fast",0.2);
    $("#fototaguacomun").css("fast",0.2);
    $("#fototucuquere").css("fast",0.2);
    $("#fotopatoreal").css("fast",0.2);
    $("#fotohuala").css("fast",0.2);
    $("#fotopeuco").css("fast",0.2);
    $("#fotocaranca").css("fast",0.2);
    $("#fotocaiquen").css("fast",0.2);
    $("#fotoquetruvolador").css("fast",0.2);
    $("#fotocormorandelasrocas").css("fast",0.2);
    $("#fotobandurria").css("fast",0.2);
    $("#fotoaguila").css("fast",0.2);
    $("#fotogarzacuca").css("fast",0.2);
    $("#fotocondor").css("fast",0.2);
  });

  $("#circuloalerceandino").click(function(){
    $("#fotopicaflorchico").css("fast",0.2);
    $("#fotochercan").css("fast",0.2);
    $("#fotochincol").css("fast",0.2);
    $("#fotorayaditodechiloe").css("fast",0.2);
    $("#fotodiucadechiloe").css("fast",0.2);
    $("#fototordo").css("fast",0.2);
    $("#fotocernicalo").css("fast",0.2);
    $("#fotoconcondechiloe").css("fast",0.2);
    $("#fotochoroy").css("fast",0.2);
    $("#fotopatocorrentino").css("fast",0.2);
    $("#fotomartinpescador").css("fast",0.2);
    $("#fotopilpilenaustral").css("fast",0.2);
    $("#fototucuquere").css("fast",0.2);
    $("#fotoaguilucho").css("fast",0.2);
    $("#fototaguacomun").css("fast",0.2);
    $("#fotocaranca").css("fast",0.2);
    $("#fotoquetruvolador").css("fast",0.2);
    $("#fotocormorandelasrocas").css("fast",0.2);
    $("#fotobandurria").css("fast",0.2);
    $("#fotoaguila").css("fast",0.2);
    $("#fotogarzacuca").css("fast",0.2);
    $("#fotohuala").css("fast",0.2);
  });


  $("#circulochiloe").click(function(){
    $("#fotocachudito").css("fast",0.2);
    $("#fotopicaflorchico").css("fast",0.2);
    $("#fotochercan").css("fast",0.2);
    $("#fotochincol").css("fast",0.2);
    $("#fotohuethuet").css("fast",0.2);
    $("#fototordo").css("fast",0.2);
    $("#fototorcaza").css("fast",0.2);
    $("#fotochoroy").css("fast",0.2);
    $("#fotopatocorrentino").css("fast",0.2);
    $("#fotomartinpescador").css("fast",0.2);
    $("#fotoaguilucho").css("fast",0.2);
    $("#fototucuquere").css("fast",0.2);
    $("#fotopatoreal").css("fast",0.2);
    $("#fotopeuco").css("fast",0.2);
    $("#fotocaiquen").css("fast",0.2);
    $("#fotoquetruvolador").css("fast",0.2);
    $("#fotobandurria").css("fast",0.2);
    $("#fotoaguila").css("fast",0.2);
    $("#fotohuala").css("fast",0.2);
    $("#fotocondor").css("fast",0.2);
  });

  $("#circulohornopiren").click(function(){
    $("#fotocachudito").css("fast",0.2);
    $("#fotopicaflorchico").css("fast",0.2);
    $("#fotochercan").css("fast",0.2);
    $("#fotochincol").css("fast",0.2);
    $("#fotorayaditodechiloe").css("fast",0.2);
    $("#fotodiucadechiloe").css("fast",0.2);
    $("#fotohuethuet").css("fast",0.2);
    $("#fototordo").css("fast",0.2);
    $("#fotocernicalo").css("fast",0.2);
    $("#fototorcaza").css("fast",0.2);
    $("#fotochoroy").css("fast",0.2);
    $("#fotopatocorrentino").css("fast",0.2);
    $("#fotomartinpescador").css("fast",0.2);
    $("#fotoaguilucho").css("fast",0.2);
    $("#fototucuquere").css("fast",0.2);
    $("#fotopatoreal").css("fast",0.2);
    $("#fotopeuco").css("fast",0.2);
    $("#fotocaiquen").css("fast",0.2);
    $("#fotocaranca").css("fast",0.2);
    $("#fotocormorandelasrocas").css("fast",0.2);
    $("#fotogarzacuca").css("fast",0.2);
    $("#fotobandurria").css("fast",0.2);
    $("#fotoaguila").css("fast",0.2);
    $("#fotohuala").css("fast",0.2);
  }); 
})