$(document).ready(function(){

  var pajaro = $(".fotopajaro")
  var titulos = $("#titulo")

  pajaro.mouseenter(function(){
      $(this).fadeTo("fast",1);
   
  });

  pajaro.mouseleave(function(){
    $(this).fadeTo("fast",0.8);
   
  });

  pajaro.click(function(){
    $(this).fadeTo("fast",1);
    $(titulos).hide('fast');

   
  });

  $("#fotocondor").click(function(){
    $("#condor").show('fast');
    $("#garza").hide('fast');
    $("#huala"). hide('fast');
    $("#aguila").hide('fast');
    $("#bandurria").hide('fast');
    $("#cormoran").hide('fast');
    $("#quetru").hide('fast');
    $("#caiquen").hide('fast');
    $("#caranca").hide('fast');
    $("#peuco").hide('fast');
    $("#tagua").hide('fast');
    $("#aguilucho").hide('fast');
    $("#patoreal").hide('fast');
    $("#tucuquere").hide('fast');
    $("#carpintero").hide('fast');
    $("#pilpilen").hide('fast');
    $("#martinpescador").hide('fast');
    $("#cortacorriente").hide('fast');
    $("#choroy").hide('fast');
    $("#torcaza").hide('fast');
    $("#concon").hide('fast');
    $("#cernicalo").hide('fast');
    $("#tordo").hide('fast');
    $("#huethuet").hide('fast');
    $("#diuca").hide('fast');
    $("#chincol").hide('fast');
    $("#rayadito").hide('fast');
    $("#chercan").hide('fast');
    $("#picaflor").hide('fast');
    $("#cachudito").hide('fast');
    

  });

  $("#fotogarzacuca").click(function(){
    $("#condor").hide('fast');
    $("#garza").show('fast');
    $("#huala"). hide('fast');
    $("#aguila").hide('fast');
    $("#bandurria").hide('fast');
    $("#cormoran").hide('fast');
    $("#quetru").hide('fast');
    $("#caiquen").hide('fast');
    $("#caranca").hide('fast');
    $("#peuco").hide('fast');
    $("#tagua").hide('fast');
    $("#aguilucho").hide('fast');
    $("#patoreal").hide('fast');
    $("#tucuquere").hide('fast');
    $("#carpintero").hide('fast');
    $("#pilpilen").hide('fast');
    $("#martinpescador").hide('fast');
    $("#cortacorriente").hide('fast');
    $("#choroy").hide('fast');
    $("#torcaza").hide('fast');
    $("#concon").hide('fast');
    $("#cernicalo").hide('fast');
    $("#tordo").hide('fast');
    $("#huethuet").hide('fast');
    $("#diuca").hide('fast');
    $("#chincol").hide('fast');
    $("#rayadito").hide('fast');
    $("#chercan").hide('fast');
    $("#picaflor").hide('fast');
    $("#cachudito").hide('fast');
    
  });

  $("#fotohuala").click(function(){
    $("#condor").hide('fast');
    $("#garza").hide('fast');
    $("#huala"). show('fast');
    $("#aguila").hide('fast');
    $("#bandurria").hide('fast');
    $("#cormoran").hide('fast');
    $("#quetru").hide('fast');
    $("#caiquen").hide('fast');
    $("#caranca").hide('fast');
    $("#peuco").hide('fast');
    $("#tagua").hide('fast');
    $("#aguilucho").hide('fast');
    $("#patoreal").hide('fast');
    $("#tucuquere").hide('fast');
    $("#carpintero").hide('fast');
    $("#pilpilen").hide('fast');
    $("#martinpescador").hide('fast');
    $("#cortacorriente").hide('fast');
    $("#choroy").hide('fast');
    $("#torcaza").hide('fast');
    $("#concon").hide('fast');
    $("#cernicalo").hide('fast');
    $("#tordo").hide('fast');
    $("#huethuet").hide('fast');
    $("#diuca").hide('fast');
    $("#chincol").hide('fast');
    $("#rayadito").hide('fast');
    $("#chercan").hide('fast');
    $("#picaflor").hide('fast');
    $("#cachudito").hide('fast');
    
  });

  $("#fotoaguila").click(function(){
    $("#condor").hide('fast');
    $("#garza").hide('fast');
    $("#huala"). hide('fast');
    $("#aguila").show('fast');
    $("#bandurria").hide('fast');
    $("#cormoran").hide('fast');
    $("#quetru").hide('fast');
    $("#caiquen").hide('fast');
    $("#caranca").hide('fast');
    $("#peuco").hide('fast');
    $("#tagua").hide('fast');
    $("#aguilucho").hide('fast');
    $("#patoreal").hide('fast');
    $("#tucuquere").hide('fast');
    $("#carpintero").hide('fast');
    $("#pilpilen").hide('fast');
    $("#martinpescador").hide('fast');
    $("#cortacorriente").hide('fast');
    $("#choroy").hide('fast');
    $("#torcaza").hide('fast');
    $("#concon").hide('fast');
    $("#cernicalo").hide('fast');
    $("#tordo").hide('fast');
    $("#huethuet").hide('fast');
    $("#diuca").hide('fast');
    $("#chincol").hide('fast');
    $("#rayadito").hide('fast');
    $("#chercan").hide('fast');
    $("#picaflor").hide('fast');
    $("#cachudito").hide('fast');
    
  });

  $("#fotobandurria").click(function(){
    $("#condor").hide('fast');
    $("#garza").hide('fast');
    $("#huala"). hide('fast');
    $("#aguila").hide('fast');
    $("#bandurria").show('fast');
    $("#cormoran").hide('fast');
    $("#quetru").hide('fast');
    $("#caiquen").hide('fast');
    $("#caranca").hide('fast');
    $("#peuco").hide('fast');
    $("#tagua").hide('fast');
    $("#aguilucho").hide('fast');
    $("#patoreal").hide('fast');
    $("#tucuquere").hide('fast');
    $("#carpintero").hide('fast');
    $("#pilpilen").hide('fast');
    $("#martinpescador").hide('fast');
    $("#cortacorriente").hide('fast');
    $("#choroy").hide('fast');
    $("#torcaza").hide('fast');
    $("#concon").hide('fast');
    $("#cernicalo").hide('fast');
    $("#tordo").hide('fast');
    $("#huethuet").hide('fast');
    $("#diuca").hide('fast');
    $("#chincol").hide('fast');
    $("#rayadito").hide('fast');
    $("#chercan").hide('fast');
    $("#picaflor").hide('fast');
    $("#cachudito").hide('fast');
    
  });

  $("#fotocormorandelasrocas").click(function(){
    $("#condor").hide('fast');
    $("#garza").hide('fast');
    $("#huala"). hide('fast');
    $("#aguila").hide('fast');
    $("#bandurria").hide('fast');
    $("#cormoran").show('fast');
    $("#quetru").hide('fast');
    $("#caiquen").hide('fast');
    $("#caranca").hide('fast');
    $("#peuco").hide('fast');
    $("#tagua").hide('fast');
    $("#aguilucho").hide('fast');
    $("#patoreal").hide('fast');
    $("#tucuquere").hide('fast');
    $("#carpintero").hide('fast');
    $("#pilpilen").hide('fast');
    $("#martinpescador").hide('fast');
    $("#cortacorriente").hide('fast');
    $("#choroy").hide('fast');
    $("#torcaza").hide('fast');
    $("#concon").hide('fast');
    $("#cernicalo").hide('fast');
    $("#tordo").hide('fast');
    $("#huethuet").hide('fast');
    $("#diuca").hide('fast');
    $("#chincol").hide('fast');
    $("#rayadito").hide('fast');
    $("#chercan").hide('fast');
    $("#picaflor").hide('fast');
    $("#cachudito").hide('fast');
    
  });

  $("#fotoquetruvolador").click(function(){
    $("#condor").hide('fast');
    $("#garza").hide('fast');
    $("#huala"). hide('fast');
    $("#aguila").hide('fast');
    $("#bandurria").hide('fast');
    $("#cormoran").hide('fast');
    $("#quetru").show('fast');
    $("#caiquen").hide('fast');
    $("#caranca").hide('fast');
    $("#peuco").hide('fast');
    $("#tagua").hide('fast');
    $("#aguilucho").hide('fast');
    $("#patoreal").hide('fast');
    $("#tucuquere").hide('fast');
    $("#carpintero").hide('fast');
    $("#pilpilen").hide('fast');
    $("#martinpescador").hide('fast');
    $("#cortacorriente").hide('fast');
    $("#choroy").hide('fast');
    $("#torcaza").hide('fast');
    $("#concon").hide('fast');
    $("#cernicalo").hide('fast');
    $("#tordo").hide('fast');
    $("#huethuet").hide('fast');
    $("#diuca").hide('fast');
    $("#chincol").hide('fast');
    $("#rayadito").hide('fast');
    $("#chercan").hide('fast');
    $("#picaflor").hide('fast');
    $("#cachudito").hide('fast');
    
  });

  $("#fotocaiquen").click(function(){
    $("#condor").hide('fast');
    $("#garza").hide('fast');
    $("#huala"). hide('fast');
    $("#aguila").hide('fast');
    $("#bandurria").hide('fast');
    $("#cormoran").hide('fast');
    $("#quetru").hide('fast');
    $("#caiquen").show('fast');
    $("#caranca").hide('fast');
    $("#peuco").hide('fast');
    $("#tagua").hide('fast');
    $("#aguilucho").hide('fast');
    $("#patoreal").hide('fast');
    $("#tucuquere").hide('fast');
    $("#carpintero").hide('fast');
    $("#pilpilen").hide('fast');
    $("#martinpescador").hide('fast');
    $("#cortacorriente").hide('fast');
    $("#choroy").hide('fast');
    $("#torcaza").hide('fast');
    $("#concon").hide('fast');
    $("#cernicalo").hide('fast');
    $("#tordo").hide('fast');
    $("#huethuet").hide('fast');
    $("#diuca").hide('fast');
    $("#chincol").hide('fast');
    $("#rayadito").hide('fast');
    $("#chercan").hide('fast');
    $("#picaflor").hide('fast');
    $("#cachudito").hide('fast');
    
  });

  $("#fotocaranca").click(function(){
    $("#condor").hide('fast');
    $("#garza").hide('fast');
    $("#huala"). hide('fast');
    $("#aguila").hide('fast');
    $("#bandurria").hide('fast');
    $("#cormoran").hide('fast');
    $("#quetru").hide('fast');
    $("#caiquen").hide('fast');
    $("#caranca").show('fast');
    $("#peuco").hide('fast');
    $("#tagua").hide('fast');
    $("#aguilucho").hide('fast');
    $("#patoreal").hide('fast');
    $("#tucuquere").hide('fast');
    $("#carpintero").hide('fast');
    $("#pilpilen").hide('fast');
    $("#martinpescador").hide('fast');
    $("#cortacorriente").hide('fast');
    $("#choroy").hide('fast');
    $("#torcaza").hide('fast');
    $("#concon").hide('fast');
    $("#cernicalo").hide('fast');
    $("#tordo").hide('fast');
    $("#huethuet").hide('fast');
    $("#diuca").hide('fast');
    $("#chincol").hide('fast');
    $("#rayadito").hide('fast');
    $("#chercan").hide('fast');
    $("#picaflor").hide('fast');
    $("#cachudito").hide('fast');
    
  });

  $("#fotopeuco").click(function(){
    $("#condor").hide('fast');
    $("#garza").hide('fast');
    $("#huala"). hide('fast');
    $("#aguila").hide('fast');
    $("#bandurria").hide('fast');
    $("#cormoran").hide('fast');
    $("#quetru").hide('fast');
    $("#caiquen").hide('fast');
    $("#caranca").hide('fast');
    $("#peuco").show('fast');
    $("#tagua").hide('fast');
    $("#aguilucho").hide('fast');
    $("#patoreal").hide('fast');
    $("#tucuquere").hide('fast');
    $("#carpintero").hide('fast');
    $("#pilpilen").hide('fast');
    $("#martinpescador").hide('fast');
    $("#cortacorriente").hide('fast');
    $("#choroy").hide('fast');
    $("#torcaza").hide('fast');
    $("#concon").hide('fast');
    $("#cernicalo").hide('fast');
    $("#tordo").hide('fast');
    $("#huethuet").hide('fast');
    $("#diuca").hide('fast');
    $("#chincol").hide('fast');
    $("#rayadito").hide('fast');
    $("#chercan").hide('fast');
    $("#picaflor").hide('fast');
    $("#cachudito").hide('fast');
    
  });

  $("#fototaguacomun").click(function(){
    $("#condor").hide('fast');
    $("#garza").hide('fast');
    $("#huala"). hide('fast');
    $("#aguila").hide('fast');
    $("#bandurria").hide('fast');
    $("#cormoran").hide('fast');
    $("#quetru").hide('fast');
    $("#caiquen").hide('fast');
    $("#caranca").hide('fast');
    $("#peuco").hide('fast');
    $("#tagua").show('fast');
    $("#aguilucho").hide('fast');
    $("#patoreal").hide('fast');
    $("#tucuquere").hide('fast');
    $("#carpintero").hide('fast');
    $("#pilpilen").hide('fast');
    $("#martinpescador").hide('fast');
    $("#cortacorriente").hide('fast');
    $("#choroy").hide('fast');
    $("#torcaza").hide('fast');
    $("#concon").hide('fast');
    $("#cernicalo").hide('fast');
    $("#tordo").hide('fast');
    $("#huethuet").hide('fast');
    $("#diuca").hide('fast');
    $("#chincol").hide('fast');
    $("#rayadito").hide('fast');
    $("#chercan").hide('fast');
    $("#picaflor").hide('fast');
    $("#cachudito").hide('fast');
    
  });

  $("#fotoaguilucho").click(function(){
    $("#condor").hide('fast');
    $("#garza").hide('fast');
    $("#huala"). hide('fast');
    $("#aguila").hide('fast');
    $("#bandurria").hide('fast');
    $("#cormoran").hide('fast');
    $("#quetru").hide('fast');
    $("#caiquen").hide('fast');
    $("#caranca").hide('fast');
    $("#peuco").hide('fast');
    $("#tagua").hide('fast');
    $("#aguilucho").show('fast');
    $("#patoreal").hide('fast');
    $("#tucuquere").hide('fast');
    $("#carpintero").hide('fast');
    $("#pilpilen").hide('fast');
    $("#martinpescador").hide('fast');
    $("#cortacorriente").hide('fast');
    $("#choroy").hide('fast');
    $("#torcaza").hide('fast');
    $("#concon").hide('fast');
    $("#cernicalo").hide('fast');
    $("#tordo").hide('fast');
    $("#huethuet").hide('fast');
    $("#diuca").hide('fast');
    $("#chincol").hide('fast');
    $("#rayadito").hide('fast');
    $("#chercan").hide('fast');
    $("#picaflor").hide('fast');
    $("#cachudito").hide('fast');
   
  });

  $("#fotopatoreal").click(function(){
    $("#condor").hide('fast');
    $("#garza").hide('fast');
    $("#huala"). hide('fast');
    $("#aguila").hide('fast');
    $("#bandurria").hide('fast');
    $("#cormoran").hide('fast');
    $("#quetru").hide('fast');
    $("#caiquen").hide('fast');
    $("#caranca").hide('fast');
    $("#peuco").hide('fast');
    $("#tagua").hide('fast');
    $("#aguilucho").hide('fast');
    $("#patoreal").show('fast');
    $("#tucuquere").hide('fast');
    $("#carpintero").hide('fast');
    $("#pilpilen").hide('fast');
    $("#martinpescador").hide('fast');
    $("#cortacorriente").hide('fast');
    $("#choroy").hide('fast');
    $("#torcaza").hide('fast');
    $("#concon").hide('fast');
    $("#cernicalo").hide('fast');
    $("#tordo").hide('fast');
    $("#huethuet").hide('fast');
    $("#diuca").hide('fast');
    $("#chincol").hide('fast');
    $("#rayadito").hide('fast');
    $("#chercan").hide('fast');
    $("#picaflor").hide('fast');
    $("#cachudito").hide('fast');
   
  });

  $("#fototucuquere").click(function(){
    $("#condor").hide('fast');
    $("#garza").hide('fast');
    $("#huala"). hide('fast');
    $("#aguila").hide('fast');
    $("#bandurria").hide('fast');
    $("#cormoran").hide('fast');
    $("#quetru").hide('fast');
    $("#caiquen").hide('fast');
    $("#caranca").hide('fast');
    $("#peuco").hide('fast');
    $("#tagua").hide('fast');
    $("#aguilucho").hide('fast');
    $("#patoreal").hide('fast');
    $("#tucuquere").show('fast');
    $("#carpintero").hide('fast');
    $("#pilpilen").hide('fast');
    $("#martinpescador").hide('fast');
    $("#cortacorriente").hide('fast');
    $("#choroy").hide('fast');
    $("#torcaza").hide('fast');
    $("#concon").hide('fast');
    $("#cernicalo").hide('fast');
    $("#tordo").hide('fast');
    $("#huethuet").hide('fast');
    $("#diuca").hide('fast');
    $("#chincol").hide('fast');
    $("#rayadito").hide('fast');
    $("#chercan").hide('fast');
    $("#picaflor").hide('fast');
    $("#cachudito").hide('fast');
   
  });

  $("#fotocarpinteronegro").click(function(){
    $("#condor").hide('fast');
    $("#garza").hide('fast');
    $("#huala"). hide('fast');
    $("#aguila").hide('fast');
    $("#bandurria").hide('fast');
    $("#cormoran").hide('fast');
    $("#quetru").hide('fast');
    $("#caiquen").hide('fast');
    $("#caranca").hide('fast');
    $("#peuco").hide('fast');
    $("#tagua").hide('fast');
    $("#aguilucho").hide('fast');
    $("#patoreal").hide('fast');
    $("#tucuquere").hide('fast');
    $("#carpintero").show('fast');
    $("#pilpilen").hide('fast');
    $("#martinpescador").hide('fast');
    $("#cortacorriente").hide('fast');
    $("#choroy").hide('fast');
    $("#torcaza").hide('fast');
    $("#concon").hide('fast');
    $("#cernicalo").hide('fast');
    $("#tordo").hide('fast');
    $("#huethuet").hide('fast');
    $("#diuca").hide('fast');
    $("#chincol").hide('fast');
    $("#rayadito").hide('fast');
    $("#chercan").hide('fast');
    $("#picaflor").hide('fast');
    $("#cachudito").hide('fast');
   
  });

  $("#fotopilpilenaustral").click(function(){
    $("#condor").hide('fast');
    $("#garza").hide('fast');
    $("#huala"). hide('fast');
    $("#aguila").hide('fast');
    $("#bandurria").hide('fast');
    $("#cormoran").hide('fast');
    $("#quetru").hide('fast');
    $("#caiquen").hide('fast');
    $("#caranca").hide('fast');
    $("#peuco").hide('fast');
    $("#tagua").hide('fast');
    $("#aguilucho").hide('fast');
    $("#patoreal").hide('fast');
    $("#tucuquere").hide('fast');
    $("#carpintero").hide('fast');
    $("#pilpilen").show('fast');
    $("#martinpescador").hide('fast');
    $("#cortacorriente").hide('fast');
    $("#choroy").hide('fast');
    $("#torcaza").hide('fast');
    $("#concon").hide('fast');
    $("#cernicalo").hide('fast');
    $("#tordo").hide('fast');
    $("#huethuet").hide('fast');
    $("#diuca").hide('fast');
    $("#chincol").hide('fast');
    $("#rayadito").hide('fast');
    $("#chercan").hide('fast');
    $("#picaflor").hide('fast');
    $("#cachudito").hide('fast');
   
  });

  $("#fotomartinpescador").click(function(){
    $("#condor").hide('fast');
    $("#garza").hide('fast');
    $("#huala"). hide('fast');
    $("#aguila").hide('fast');
    $("#bandurria").hide('fast');
    $("#cormoran").hide('fast');
    $("#quetru").hide('fast');
    $("#caiquen").hide('fast');
    $("#caranca").hide('fast');
    $("#peuco").hide('fast');
    $("#tagua").hide('fast');
    $("#aguilucho").hide('fast');
    $("#patoreal").hide('fast');
    $("#tucuquere").hide('fast');
    $("#carpintero").hide('fast');
    $("#pilpilen").hide('fast');
    $("#martinpescador").show('fast');
    $("#cortacorriente").hide('fast');
    $("#choroy").hide('fast');
    $("#torcaza").hide('fast');
    $("#concon").hide('fast');
    $("#cernicalo").hide('fast');
    $("#tordo").hide('fast');
    $("#huethuet").hide('fast');
    $("#diuca").hide('fast');
    $("#chincol").hide('fast');
    $("#rayadito").hide('fast');
    $("#chercan").hide('fast');
    $("#picaflor").hide('fast');
    $("#cachudito").hide('fast');
   
  });

  $("#fotopatocorrentino").click(function(){
    $("#condor").hide('fast');
    $("#garza").hide('fast');
    $("#huala"). hide('fast');
    $("#aguila").hide('fast');
    $("#bandurria").hide('fast');
    $("#cormoran").hide('fast');
    $("#quetru").hide('fast');
    $("#caiquen").hide('fast');
    $("#caranca").hide('fast');
    $("#peuco").hide('fast');
    $("#tagua").hide('fast');
    $("#aguilucho").hide('fast');
    $("#patoreal").hide('fast');
    $("#tucuquere").hide('fast');
    $("#carpintero").hide('fast');
    $("#pilpilen").hide('fast');
    $("#martinpescador").hide('fast');
    $("#cortacorriente").show('fast');
    $("#choroy").hide('fast');
    $("#torcaza").hide('fast');
    $("#concon").hide('fast');
    $("#cernicalo").hide('fast');
    $("#tordo").hide('fast');
    $("#huethuet").hide('fast');
    $("#diuca").hide('fast');
    $("#chincol").hide('fast');
    $("#rayadito").hide('fast');
    $("#chercan").hide('fast');
    $("#picaflor").hide('fast');
    $("#cachudito").hide('fast');
   
  });

  $("#fotochoroy").click(function(){
    $("#condor").hide('fast');
    $("#garza").hide('fast');
    $("#huala"). hide('fast');
    $("#aguila").hide('fast');
    $("#bandurria").hide('fast');
    $("#cormoran").hide('fast');
    $("#quetru").hide('fast');
    $("#caiquen").hide('fast');
    $("#caranca").hide('fast');
    $("#peuco").hide('fast');
    $("#tagua").hide('fast');
    $("#aguilucho").hide('fast');
    $("#patoreal").hide('fast');
    $("#tucuquere").hide('fast');
    $("#carpintero").hide('fast');
    $("#pilpilen").hide('fast');
    $("#martinpescador").hide('fast');
    $("#cortacorriente").hide('fast');
    $("#choroy").show('fast');
    $("#torcaza").hide('fast');
    $("#concon").hide('fast');
    $("#cernicalo").hide('fast');
    $("#tordo").hide('fast');
    $("#huethuet").hide('fast');
    $("#diuca").hide('fast');
    $("#chincol").hide('fast');
    $("#rayadito").hide('fast');
    $("#chercan").hide('fast');
    $("#picaflor").hide('fast');
    $("#cachudito").hide('fast');
   
  });

  $("#fototorcaza").click(function(){
    $("#condor").hide('fast');
    $("#garza").hide('fast');
    $("#huala"). hide('fast');
    $("#aguila").hide('fast');
    $("#bandurria").hide('fast');
    $("#cormoran").hide('fast');
    $("#quetru").hide('fast');
    $("#caiquen").hide('fast');
    $("#caranca").hide('fast');
    $("#peuco").hide('fast');
    $("#tagua").hide('fast');
    $("#aguilucho").hide('fast');
    $("#patoreal").hide('fast');
    $("#tucuquere").hide('fast');
    $("#carpintero").hide('fast');
    $("#pilpilen").hide('fast');
    $("#martinpescador").hide('fast');
    $("#cortacorriente").hide('fast');
    $("#choroy").hide('fast');
    $("#torcaza").show('fast');
    $("#concon").hide('fast');
    $("#cernicalo").hide('fast');
    $("#tordo").hide('fast');
    $("#huethuet").hide('fast');
    $("#diuca").hide('fast');
    $("#chincol").hide('fast');
    $("#rayadito").hide('fast');
    $("#chercan").hide('fast');
    $("#picaflor").hide('fast');
    $("#cachudito").hide('fast');
   
  });

  $("#fotoconcondechiloe").click(function(){
    $("#condor").hide('fast');
    $("#garza").hide('fast');
    $("#huala"). hide('fast');
    $("#aguila").hide('fast');
    $("#bandurria").hide('fast');
    $("#cormoran").hide('fast');
    $("#quetru").hide('fast');
    $("#caiquen").hide('fast');
    $("#caranca").hide('fast');
    $("#peuco").hide('fast');
    $("#tagua").hide('fast');
    $("#aguilucho").hide('fast');
    $("#patoreal").hide('fast');
    $("#tucuquere").hide('fast');
    $("#carpintero").hide('fast');
    $("#pilpilen").hide('fast');
    $("#martinpescador").hide('fast');
    $("#cortacorriente").hide('fast');
    $("#choroy").hide('fast');
    $("#torcaza").hide('fast');
    $("#concon").show('fast');
    $("#cernicalo").hide('fast');
    $("#tordo").hide('fast');
    $("#huethuet").hide('fast');
    $("#diuca").hide('fast');
    $("#chincol").hide('fast');
    $("#rayadito").hide('fast');
    $("#chercan").hide('fast');
    $("#picaflor").hide('fast');
    $("#cachudito").hide('fast');
   
  });

  $("#fotocernicalo").click(function(){
    $("#condor").hide('fast');
    $("#garza").hide('fast');
    $("#huala"). hide('fast');
    $("#aguila").hide('fast');
    $("#bandurria").hide('fast');
    $("#cormoran").hide('fast');
    $("#quetru").hide('fast');
    $("#caiquen").hide('fast');
    $("#caranca").hide('fast');
    $("#peuco").hide('fast');
    $("#tagua").hide('fast');
    $("#aguilucho").hide('fast');
    $("#patoreal").hide('fast');
    $("#tucuquere").hide('fast');
    $("#carpintero").hide('fast');
    $("#pilpilen").hide('fast');
    $("#martinpescador").hide('fast');
    $("#cortacorriente").hide('fast');
    $("#choroy").hide('fast');
    $("#torcaza").hide('fast');
    $("#concon").hide('fast');
    $("#cernicalo").show('fast');
    $("#tordo").hide('fast');
    $("#huethuet").hide('fast');
    $("#diuca").hide('fast');
    $("#chincol").hide('fast');
    $("#rayadito").hide('fast');
    $("#chercan").hide('fast');
    $("#picaflor").hide('fast');
    $("#cachudito").hide('fast');
   
  });

  $("#fototordo").click(function(){
    $("#condor").hide('fast');
    $("#garza").hide('fast');
    $("#huala"). hide('fast');
    $("#aguila").hide('fast');
    $("#bandurria").hide('fast');
    $("#cormoran").hide('fast');
    $("#quetru").hide('fast');
    $("#caiquen").hide('fast');
    $("#caranca").hide('fast');
    $("#peuco").hide('fast');
    $("#tagua").hide('fast');
    $("#aguilucho").hide('fast');
    $("#patoreal").hide('fast');
    $("#tucuquere").hide('fast');
    $("#carpintero").hide('fast');
    $("#pilpilen").hide('fast');
    $("#martinpescador").hide('fast');
    $("#cortacorriente").hide('fast');
    $("#choroy").hide('fast');
    $("#torcaza").hide('fast');
    $("#concon").hide('fast');
    $("#cernicalo").hide('fast');
    $("#tordo").show('fast');
    $("#huethuet").hide('fast');
    $("#diuca").hide('fast');
    $("#chincol").hide('fast');
    $("#rayadito").hide('fast');
    $("#chercan").hide('fast');
    $("#picaflor").hide('fast');
    $("#cachudito").hide('fast');
   
  });

  $("#fotohuethuet").click(function(){
    $("#condor").hide('fast');
    $("#garza").hide('fast');
    $("#huala"). hide('fast');
    $("#aguila").hide('fast');
    $("#bandurria").hide('fast');
    $("#cormoran").hide('fast');
    $("#quetru").hide('fast');
    $("#caiquen").hide('fast');
    $("#caranca").hide('fast');
    $("#peuco").hide('fast');
    $("#tagua").hide('fast');
    $("#aguilucho").hide('fast');
    $("#patoreal").hide('fast');
    $("#tucuquere").hide('fast');
    $("#carpintero").hide('fast');
    $("#pilpilen").hide('fast');
    $("#martinpescador").hide('fast');
    $("#cortacorriente").hide('fast');
    $("#choroy").hide('fast');
    $("#torcaza").hide('fast');
    $("#concon").hide('fast');
    $("#cernicalo").hide('fast');
    $("#tordo").hide('fast');
    $("#huethuet").show('fast');
    $("#diuca").hide('fast');
    $("#chincol").hide('fast');
    $("#rayadito").hide('fast');
    $("#chercan").hide('fast');
    $("#picaflor").hide('fast');
    $("#cachudito").hide('fast');
   
  });

  $("#fotodiucadechiloe").click(function(){
    $("#condor").hide('fast');
    $("#garza").hide('fast');
    $("#huala"). hide('fast');
    $("#aguila").hide('fast');
    $("#bandurria").hide('fast');
    $("#cormoran").hide('fast');
    $("#quetru").hide('fast');
    $("#caiquen").hide('fast');
    $("#caranca").hide('fast');
    $("#peuco").hide('fast');
    $("#tagua").hide('fast');
    $("#aguilucho").hide('fast');
    $("#patoreal").hide('fast');
    $("#tucuquere").hide('fast');
    $("#carpintero").hide('fast');
    $("#pilpilen").hide('fast');
    $("#martinpescador").hide('fast');
    $("#cortacorriente").hide('fast');
    $("#choroy").hide('fast');
    $("#torcaza").hide('fast');
    $("#concon").hide('fast');
    $("#cernicalo").hide('fast');
    $("#tordo").hide('fast');
    $("#huethuet").hide('fast');
    $("#diuca").show('fast');
    $("#chincol").hide('fast');
    $("#rayadito").hide('fast');
    $("#chercan").hide('fast');
    $("#picaflor").hide('fast');
    $("#cachudito").hide('fast');
   
  });

  $("#fotochincol").click(function(){
    $("#condor").hide('fast');
    $("#garza").hide('fast');
    $("#huala"). hide('fast');
    $("#aguila").hide('fast');
    $("#bandurria").hide('fast');
    $("#cormoran").hide('fast');
    $("#quetru").hide('fast');
    $("#caiquen").hide('fast');
    $("#caranca").hide('fast');
    $("#peuco").hide('fast');
    $("#tagua").hide('fast');
    $("#aguilucho").hide('fast');
    $("#patoreal").hide('fast');
    $("#tucuquere").hide('fast');
    $("#carpintero").hide('fast');
    $("#pilpilen").hide('fast');
    $("#martinpescador").hide('fast');
    $("#cortacorriente").hide('fast');
    $("#choroy").hide('fast');
    $("#torcaza").hide('fast');
    $("#concon").hide('fast');
    $("#cernicalo").hide('fast');
    $("#tordo").hide('fast');
    $("#huethuet").hide('fast');
    $("#diuca").hide('fast');
    $("#chincol").show('fast');
    $("#rayadito").hide('fast');
    $("#chercan").hide('fast');
    $("#picaflor").hide('fast');
    $("#cachudito").hide('fast');
   
  });

  $("#fotorayaditodechiloe").click(function(){
    $("#condor").hide('fast');
    $("#garza").hide('fast');
    $("#huala"). hide('fast');
    $("#aguila").hide('fast');
    $("#bandurria").hide('fast');
    $("#cormoran").hide('fast');
    $("#quetru").hide('fast');
    $("#caiquen").hide('fast');
    $("#caranca").hide('fast');
    $("#peuco").hide('fast');
    $("#tagua").hide('fast');
    $("#aguilucho").hide('fast');
    $("#patoreal").hide('fast');
    $("#tucuquere").hide('fast');
    $("#carpintero").hide('fast');
    $("#pilpilen").hide('fast');
    $("#martinpescador").hide('fast');
    $("#cortacorriente").hide('fast');
    $("#choroy").hide('fast');
    $("#torcaza").hide('fast');
    $("#concon").hide('fast');
    $("#cernicalo").hide('fast');
    $("#tordo").hide('fast');
    $("#huethuet").hide('fast');
    $("#diuca").hide('fast');
    $("#chincol").hide('fast');
    $("#rayadito").show('fast');
    $("#chercan").hide('fast');
    $("#picaflor").hide('fast');
    $("#cachudito").hide('fast');
   
  });

  $("#fotochercan").click(function(){
    $("#condor").hide('fast');
    $("#garza").hide('fast');
    $("#huala"). hide('fast');
    $("#aguila").hide('fast');
    $("#bandurria").hide('fast');
    $("#cormoran").hide('fast');
    $("#quetru").hide('fast');
    $("#caiquen").hide('fast');
    $("#caranca").hide('fast');
    $("#peuco").hide('fast');
    $("#tagua").hide('fast');
    $("#aguilucho").hide('fast');
    $("#patoreal").hide('fast');
    $("#tucuquere").hide('fast');
    $("#carpintero").hide('fast');
    $("#pilpilen").hide('fast');
    $("#martinpescador").hide('fast');
    $("#cortacorriente").hide('fast');
    $("#choroy").hide('fast');
    $("#torcaza").hide('fast');
    $("#concon").hide('fast');
    $("#cernicalo").hide('fast');
    $("#tordo").hide('fast');
    $("#huethuet").hide('fast');
    $("#diuca").hide('fast');
    $("#chincol").hide('fast');
    $("#rayadito").hide('fast');
    $("#chercan").show('fast');
    $("#picaflor").hide('fast');
    $("#cachudito").hide('fast');
   
  });

  $("#fotopicaflorchico").click(function(){
    $("#condor").hide('fast');
    $("#garza").hide('fast');
    $("#huala"). hide('fast');
    $("#aguila").hide('fast');
    $("#bandurria").hide('fast');
    $("#cormoran").hide('fast');
    $("#quetru").hide('fast');
    $("#caiquen").hide('fast');
    $("#caranca").hide('fast');
    $("#peuco").hide('fast');
    $("#tagua").hide('fast');
    $("#aguilucho").hide('fast');
    $("#patoreal").hide('fast');
    $("#tucuquere").hide('fast');
    $("#carpintero").hide('fast');
    $("#pilpilen").hide('fast');
    $("#martinpescador").hide('fast');
    $("#cortacorriente").hide('fast');
    $("#choroy").hide('fast');
    $("#torcaza").hide('fast');
    $("#concon").hide('fast');
    $("#cernicalo").hide('fast');
    $("#tordo").hide('fast');
    $("#huethuet").hide('fast');
    $("#diuca").hide('fast');
    $("#chincol").hide('fast');
    $("#rayadito").hide('fast');
    $("#chercan").hide('fast');
    $("#picaflor").show('fast');
    $("#cachudito").hide('fast');
   
  });

  $("#fotocachudito").click(function(){
    $("#condor").hide('fast');
    $("#garza").hide('fast');
    $("#huala"). hide('fast');
    $("#aguila").hide('fast');
    $("#bandurria").hide('fast');
    $("#cormoran").hide('fast');
    $("#quetru").hide('fast');
    $("#caiquen").hide('fast');
    $("#caranca").hide('fast');
    $("#peuco").hide('fast');
    $("#tagua").hide('fast');
    $("#aguilucho").hide('fast');
    $("#patoreal").hide('fast');
    $("#tucuquere").hide('fast');
    $("#carpintero").hide('fast');
    $("#pilpilen").hide('fast');
    $("#martinpescador").hide('fast');
    $("#cortacorriente").hide('fast');
    $("#choroy").hide('fast');
    $("#torcaza").hide('fast');
    $("#concon").hide('fast');
    $("#cernicalo").hide('fast');
    $("#tordo").hide('fast');
    $("#huethuet").hide('fast');
    $("#diuca").hide('fast');
    $("#chincol").hide('fast');
    $("#rayadito").hide('fast');
    $("#chercan").hide('fast');
    $("#picaflor").hide('fast');
    $("#cachudito").show('fast');
   
  });

  $("#fotocondor").click(function(){
    $("#condor").show('fast');
    $("#garza").hide('fast');
    $("#huala"). hide('fast');
    $("#aguila").hide('fast');
    $("#bandurria").hide('fast');
    $("#cormoran").hide('fast');
    $("#quetru").hide('fast');
    $("#caiquen").hide('fast');
    $("#caranca").hide('fast');
    $("#peuco").hide('fast');
    $("#tagua").hide('fast');
    $("#aguilucho").hide('fast');
    $("#patoreal").hide('fast');
    $("#tucuquere").hide('fast');
    $("#carpintero").hide('fast');
    $("#pilpilen").hide('fast');
    $("#martinpescador").hide('fast');
    $("#cortacorriente").hide('fast');
    $("#choroy").hide('fast');
    $("#torcaza").hide('fast');
    $("#concon").hide('fast');
    $("#cernicalo").hide('fast');
    $("#tordo").hide('fast');
    $("#huethuet").hide('fast');
    $("#diuca").hide('fast');
    $("#chincol").hide('fast');
    $("#rayadito").hide('fast');
    $("#chercan").hide('fast');
    $("#picaflor").hide('fast');
    $("#cachudito").hide('fast');
   
  });

  $("#fotocondor").click(function(){
    $("#condor").show('fast');
    $("#garza").hide('fast');
    $("#huala"). hide('fast');
    $("#aguila").hide('fast');
    $("#bandurria").hide('fast');
    $("#cormoran").hide('fast');
    $("#quetru").hide('fast');
    $("#caiquen").hide('fast');
    $("#caranca").hide('fast');
    $("#peuco").hide('fast');
    $("#tagua").hide('fast');
    $("#aguilucho").hide('fast');
    $("#patoreal").hide('fast');
    $("#tucuquere").hide('fast');
    $("#carpintero").hide('fast');
    $("#pilpilen").hide('fast');
    $("#martinpescador").hide('fast');
    $("#cortacorriente").hide('fast');
    $("#choroy").hide('fast');
    $("#torcaza").hide('fast');
    $("#concon").hide('fast');
    $("#cernicalo").hide('fast');
    $("#tordo").hide('fast');
    $("#huethuet").hide('fast');
    $("#diuca").hide('fast');
    $("#chincol").hide('fast');
    $("#rayadito").hide('fast');
    $("#chercan").hide('fast');
    $("#picaflor").hide('fast');
    $("#cachudito").hide('fast');
   
  });

  $("#fotocondor").click(function(){
    $("#condor").show('fast');
    $("#garza").hide('fast');
    $("#huala"). hide('fast');
    $("#aguila").hide('fast');
    $("#bandurria").hide('fast');
    $("#cormoran").hide('fast');
    $("#quetru").hide('fast');
    $("#caiquen").hide('fast');
    $("#caranca").hide('fast');
    $("#peuco").hide('fast');
    $("#tagua").hide('fast');
    $("#aguilucho").hide('fast');
    $("#patoreal").hide('fast');
    $("#tucuquere").hide('fast');
    $("#carpintero").hide('fast');
    $("#pilpilen").hide('fast');
    $("#martinpescador").hide('fast');
    $("#cortacorriente").hide('fast');
    $("#choroy").hide('fast');
    $("#torcaza").hide('fast');
    $("#concon").hide('fast');
    $("#cernicalo").hide('fast');
    $("#tordo").hide('fast');
    $("#huethuet").hide('fast');
    $("#diuca").hide('fast');
    $("#chincol").hide('fast');
    $("#rayadito").hide('fast');
    $("#chercan").hide('fast');
    $("#picaflor").hide('fast');
    $("#cachudito").hide('fast');
   
  });

  $("#circulolagunadellaja").click(function(){
    $("#fotodiucadechiloe").fadeTo("fast",0.2);
    $("#fotoconcondechiloe").fadeTo("fast",0.2);
    $("#fototorcaza").fadeTo("fast",0.2);
    $("#fotochoroy").fadeTo("fast",0.2);
    $("#fotomartinpescador").fadeTo("fast",0.2);
    $("#fotopilpilen").fadeTo("fast",0.2);
    $("#fotopatoreal").fadeTo("fast",0.2);
    $("#fotocaranca").fadeTo("fast",0.2);
    $("#fotocaiquen").fadeTo("fast",0.2);
    $("#fotoquetruvolador").fadeTo("fast",0.2);
    $("#fotohuala").fadeTo("fast",0.2);
    $("#fotocormorandelasrocas").fadeTo("fast",0.2);
    $("#fotogarzacuca").fadeTo("fast",0.2);
  });

  $("#circulononguen").click(function(){
    $("#fotocachudito").fadeTo("fast",0.2);
    $("#fotopicaflorchico").fadeTo("fast",0.2);
    $("#fotochercan").fadeTo("fast",0.2);
    $("#fotochincol").fadeTo("fast",0.2);
    $("#fotodiucadechiloe").fadeTo("fast",0.2);
    $("#fotohuethuet").fadeTo("fast",0.2);
    $("#fototordo").fadeTo("fast",0.2);
    $("#fotocernicalo").fadeTo("fast",0.2);
    $("#fotoconcondechiloe").fadeTo("fast",0.2);
    $("#fototorcaza").fadeTo("fast",0.2);
    $("#fotochoroy").fadeTo("fast",0.2);
    $("#fotopatocorrentino").fadeTo("fast",0.2);
    $("#fotomartinpescador").fadeTo("fast",0.2);
    $("#fotopilpilenaustral").fadeTo("fast",0.2);
    $("#fotocarpinteronegro").fadeTo("fast",0.2);
    $("#fototucuquere").fadeTo("fast",0.2);
    $("#fotopatoreal").fadeTo("fast",0.2);
    $("#fotopeuco").fadeTo("fast",0.2);
    $("#fotocaranca").fadeTo("fast",0.2);
    $("#fotocaiquen").fadeTo("fast",0.2);
    $("#fotoquetruvolador").fadeTo("fast",0.2);
    $("#fotocormorandelasrocas").fadeTo("fast",0.2);
    $("#fotobandurria").fadeTo("fast",0.2);
    $("#fotoaguila").fadeTo("fast",0.2);
    $("#fotogarzacuca").fadeTo("fast",0.2);
    $("#fotocondor").fadeTo("fast",0.2);
  });

  $("#circulohuerquehue").click(function(){
    $("#fotocachudito").fadeTo("fast",0.2);
    $("#fotopicaflorchico").fadeTo("fast",0.2);
    $("#fotochercan").fadeTo("fast",0.2);
    $("#fotochincol").fadeTo("fast",0.2);
    $("#fotodiucadechiloe").fadeTo("fast",0.2);
    $("#fotohuethuet").fadeTo("fast",0.2);
    $("#fototordo").fadeTo("fast",0.2);
    $("#fotocernicalo").fadeTo("fast",0.2);
    $("#fotoconcondechiloe").fadeTo("fast",0.2);
    $("#fotopatocorrentino").fadeTo("fast",0.2);
    $("#fotomartinpescador").fadeTo("fast",0.2);
    $("#fotopilpilenaustral").fadeTo("fast",0.2);
    $("#fototucuquere").fadeTo("fast",0.2);
    $("#fotopatoreal").fadeTo("fast",0.2);
    $("#fotopeuco").fadeTo("fast",0.2);
    $("#fotocaranca").fadeTo("fast",0.2);
    $("#fotocaiquen").fadeTo("fast",0.2);
    $("#fotocormorandelasrocas").fadeTo("fast",0.2);
    $("#fotobandurria").fadeTo("fast",0.2);
    $("#fotoaguila").fadeTo("fast",0.2);
    $("#fotogarzacuca").fadeTo("fast",0.2);
  });

  $("#circulovillarrica").click(function(){
    $("#fotocachudito").fadeTo("fast",0.2);
    $("#fotopicaflorchico").fadeTo("fast",0.2);
    $("#fotochincol").fadeTo("fast",0.2);
    $("#fotodiucadechiloe").fadeTo("fast",0.2);
    $("#fotohuethuet").fadeTo("fast",0.2);
    $("#fototordo").fadeTo("fast",0.2);
    $("#fotocernicalo").fadeTo("fast",0.2);
    $("#fotoconcondechiloe").fadeTo("fast",0.2);
    $("#fototorcaza").fadeTo("fast",0.2);
    $("#fotochoroy").fadeTo("fast",0.2);
    $("#fotopatocorrentino").fadeTo("fast",0.2);
    $("#fotomartinpescador").fadeTo("fast",0.2);
    $("#fotopilpilenaustral").fadeTo("fast",0.2);
    $("#fotocarpinteronegro").fadeTo("fast",0.2);
    $("#fototucuquere").fadeTo("fast",0.2);
    $("#fotocaranca").fadeTo("fast",0.2);
    $("#fotocaiquen").fadeTo("fast",0.2);
    $("#fotoquetruvolador").fadeTo("fast",0.2);
    $("#fotocormorandelasrocas").fadeTo("fast",0.2);
    $("#fotobandurria").fadeTo("fast",0.2);
    $("#fotogarzacuca").fadeTo("fast",0.2);
    $("#fotocondor").fadeTo("fast",0.2);
  });

  $("#circulonahuelbuta").click(function(){
    $("#fotochincol").fadeTo("fast",0.2);
    $("#fotodiucadechiloe").fadeTo("fast",0.2);
    $("#fototordo").fadeTo("fast",0.2);
    $("#fotoconcondechiloe").fadeTo("fast",0.2);
    $("#fototorcaza").fadeTo("fast",0.2);
    $("#fotochoroy").fadeTo("fast",0.2);
    $("#fotopatocorrentino").fadeTo("fast",0.2);
    $("#fotomartinpescador").fadeTo("fast",0.2);
    $("#fotopilpilenaustral").fadeTo("fast",0.2);
    $("#fotocaranca").fadeTo("fast",0.2);
    $("#fotocaiquen").fadeTo("fast",0.2);
    $("#fotoquetruvolador").fadeTo("fast",0.2);
    $("#fotocormorandelasrocas").fadeTo("fast",0.2);
    $("#fotohuala").fadeTo("fast",0.2);
    $("#fotogarzacuca").fadeTo("fast",0.2);
    $("#fotocondor").fadeTo("fast",0.2);
  });
  $("#circulotolhuaca").click(function(){
    $("#fotocachudito").fadeTo("fast",0.2);
    $("#fotopicaflorchico").fadeTo("fast",0.2);
    $("#fotochercan").fadeTo("fast",0.2);
    $("#fotorayaditodechiloe").fadeTo("fast",0.2);
    $("#fotochincol").fadeTo("fast",0.2);
    $("#fotodiucadechiloe").fadeTo("fast",0.2);
    $("#fotohuethuet").fadeTo("fast",0.2);
    $("#fototordo").fadeTo("fast",0.2);
    $("#fotocernicalo").fadeTo("fast",0.2);
    $("#fotoconcondechiloe").fadeTo("fast",0.2);
    $("#fotopatocorrentino").fadeTo("fast",0.2);
    $("#fotopilpilenaustral").fadeTo("fast",0.2);
    $("#fototucuquere").fadeTo("fast",0.2);
    $("#fotopatoreal").fadeTo("fast",0.2);
    $("#fotopeuco").fadeTo("fast",0.2);
    $("#fotocaranca").fadeTo("fast",0.2);
    $("#fotocaiquen").fadeTo("fast",0.2);
    $("#fotoquetruvolador").fadeTo("fast",0.2);
    $("#fotocormorandelasrocas").fadeTo("fast",0.2);
    $("#fotohuala").fadeTo("fast",0.2);
    $("#fotogarzacuca").fadeTo("fast",0.2);
  });

  $("#circuloconguillio").click(function(){
    $("#fotodiucadechiloe").fadeTo("fast",0.2);
    $("#fotoconcondechiloe").fadeTo("fast",0.2);
    $("#fototorcaza").fadeTo("fast",0.2);
    $("#fotopilpilenaustral").fadeTo("fast",0.2);
    $("#fotoaguilucho").fadeTo("fast",0.2);
    $("#fotocaranca").fadeTo("fast",0.2);
    $("#fotocaiquen").fadeTo("fast",0.2);
    $("#fotocormorandelasrocas").fadeTo("fast",0.2);
    $("#fotobandurria").fadeTo("fast",0.2);
    $("#fotoaguila").fadeTo("fast",0.2);
  });

  $("#circuloalercecostero").click(function(){
    $("#fotorayaditodechiloe").fadeTo("fast",0.2);
    $("#fotopicaflorchico").fadeTo("fast",0.2);
    $("#fotochercan").fadeTo("fast",0.2);
    $("#fotochincol").fadeTo("fast",0.2);
    $("#fotodiucadechiloe").fadeTo("fast",0.2);
    $("#fototordo").fadeTo("fast",0.2);
    $("#fotocernicalo").fadeTo("fast",0.2);
    $("#fotoconcondechiloe").fadeTo("fast",0.2);
    $("#fototorcaza").fadeTo("fast",0.2);
    $("#fotochoroy").fadeTo("fast",0.2);
    $("#fotopatocorrentino").fadeTo("fast",0.2);
    $("#fotopilpilenaustral").fadeTo("fast",0.2);
    $("#fototucuquere").fadeTo("fast",0.2);
    $("#fotoaguilucho").fadeTo("fast",0.2);
    $("#fototaguacomun").fadeTo("fast",0.2);
    $("#fotocaranca").fadeTo("fast",0.2);
    $("#fotoquetruvolador").fadeTo("fast",0.2);
    $("#fotocormorandelasrocas").fadeTo("fast",0.2);
    $("#fotobandurria").fadeTo("fast",0.2);
    $("#fotoaguila").fadeTo("fast",0.2);
    $("#fotohuala").fadeTo("fast",0.2);
    $("#fotogarzacuca").fadeTo("fast",0.2);
    $("#fotocondor").fadeTo("fast",0.2);
  });


  $("#circulopumalin").click(function(){
    $("#fotocachudito").fadeTo("fast",0.2);
    $("#fotochercan").fadeTo("fast",0.2);
    $("#fotochincol").fadeTo("fast",0.2);
    $("#fotorayaditodechiloe").fadeTo("fast",0.2);
    $("#fotohuethuet").fadeTo("fast",0.2);
    $("#fototordo").fadeTo("fast",0.2);
    $("#fotocernicalo").fadeTo("fast",0.2);
    $("#fotoconcondechiloe").fadeTo("fast",0.2);
    $("#fototorcaza").fadeTo("fast",0.2);
    $("#fotochoroy").fadeTo("fast",0.2);
    $("#fotopatocorrentino").fadeTo("fast",0.2);
    $("#fotomartinpescador").fadeTo("fast",0.2);
    $("#fotopilpilenaustral").fadeTo("fast",0.2);
    $("#fototucuquere").fadeTo("fast",0.2);
    $("#fotopatoreal").fadeTo("fast",0.2);
    $("#fototaguacomun").fadeTo("fast",0.2);
    $("#fotocaranca").fadeTo("fast",0.2);
    $("#fotocaiquen").fadeTo("fast",0.2);
    $("#fotoquetruvolador").fadeTo("fast",0.2);
    $("#fotocormorandelasrocas").fadeTo("fast",0.2);
    $("#fotohuala").fadeTo("fast",0.2);
    $("#fotoaguila").fadeTo("fast",0.2);
    $("#fotogarzacuca").fadeTo("fast",0.2);
  });


  $("#circulopuyehue").click(function(){
    $("#fotocachudito").fadeTo("fast",0.2);
    $("#fotopicaflorchico").fadeTo("fast",0.2);
    $("#fotorayaditodechiloe").fadeTo("fast",0.2);
    $("#fotochincol").fadeTo("fast",0.2);
    $("#fotodiucadechiloe").fadeTo("fast",0.2);
    $("#fototordo").fadeTo("fast",0.2);
    $("#fotocernicalo").fadeTo("fast",0.2);
    $("#fotoconcondechiloe").fadeTo("fast",0.2);
    $("#fotomartinpescador").fadeTo("fast",0.2);
    $("#fotopilpilenaustral").fadeTo("fast",0.2);
    $("#fotocarpinteronegro").fadeTo("fast",0.2);
    $("#fototucuquere").fadeTo("fast",0.2);
    $("#fotopatoreal").fadeTo("fast",0.2);
    $("#fototaguacomun").fadeTo("fast",0.2);
    $("#fotopeuco").fadeTo("fast",0.2);
    $("#fotocaranca").fadeTo("fast",0.2);
    $("#fotocaiquen").fadeTo("fast",0.2);
    $("#fotoquetruvolador").fadeTo("fast",0.2);
    $("#fotocormorandelasrocas").fadeTo("fast",0.2);
    $("#fotoaguila").fadeTo("fast",0.2);
    $("#fotogarzacuca").fadeTo("fast",0.2);
  });



  $("#circulovicenteperezrosales").click(function(){
    $("#fotocachudito").fadeTo("fast",0.2);
    $("#fotochercan").fadeTo("fast",0.2);
    $("#fotochincol").fadeTo("fast",0.2);
    $("#fotodiucadechiloe").fadeTo("fast",0.2);
    $("#fotohuethuet").fadeTo("fast",0.2);
    $("#fototordo").fadeTo("fast",0.2);
    $("#fotocernicalo").fadeTo("fast",0.2);
    $("#fotoconcondechiloe").fadeTo("fast",0.2);
    $("#fototorcaza").fadeTo("fast",0.2);
    $("#fotochoroy").fadeTo("fast",0.2);
    $("#fotomartinpescador").fadeTo("fast",0.2);
    $("#fotopilpilenaustral").fadeTo("fast",0.2);
    $("#fototucuquere").fadeTo("fast",0.2);
    $("#fotopatoreal").fadeTo("fast",0.2);
    $("#fotopeuco").fadeTo("fast",0.2);
    $("#fotohuala").fadeTo("fast",0.2);
    $("#fotocaranca").fadeTo("fast",0.2);
    $("#fotocaiquen").fadeTo("fast",0.2);
    $("#fotoquetruvolador").fadeTo("fast",0.2);
    $("#fotocormorandelasrocas").fadeTo("fast",0.2);
    $("#fotobandurria").fadeTo("fast",0.2);
    $("#fotoaguilucho").fadeTo("fast",0.2);
    $("#fotogarzacuca").fadeTo("fast",0.2);
    $("#fotocondor").fadeTo("fast",0.2);
  });


  $("#circulocorcovado").click(function(){
    $("#fotocachudito").fadeTo("fast",0.2);
    $("#fotopicaflorchico").fadeTo("fast",0.2);
    $("#fotochercan").fadeTo("fast",0.2);
    $("#fotochincol").fadeTo("fast",0.2);
    $("#fotodiucadechiloe").fadeTo("fast",0.2);
    $("#fotorayaditodechiloe").fadeTo("fast",0.2);
    $("#fotohuethuet").fadeTo("fast",0.2);
    $("#fototordo").fadeTo("fast",0.2);
    $("#fotocernicalo").fadeTo("fast",0.2);
    $("#fotoconcondechiloe").fadeTo("fast",0.2);
    $("#fototorcaza").fadeTo("fast",0.2);
    $("#fotochoroy").fadeTo("fast",0.2);
    $("#fotopatocorrentino").fadeTo("fast",0.2);
    $("#fotomartinpescador").fadeTo("fast",0.2);
    $("#fotopilpilenaustral").fadeTo("fast",0.2);
    $("#fotoaguilucho").fadeTo("fast",0.2);
    $("#fototaguacomun").fadeTo("fast",0.2);
    $("#fototucuquere").fadeTo("fast",0.2);
    $("#fotopatoreal").fadeTo("fast",0.2);
    $("#fotohuala").fadeTo("fast",0.2);
    $("#fotopeuco").fadeTo("fast",0.2);
    $("#fotocaranca").fadeTo("fast",0.2);
    $("#fotocaiquen").fadeTo("fast",0.2);
    $("#fotoquetruvolador").fadeTo("fast",0.2);
    $("#fotocormorandelasrocas").fadeTo("fast",0.2);
    $("#fotobandurria").fadeTo("fast",0.2);
    $("#fotoaguila").fadeTo("fast",0.2);
    $("#fotogarzacuca").fadeTo("fast",0.2);
    $("#fotocondor").fadeTo("fast",0.2);
  });

  $("#circuloalerceandino").click(function(){
    $("#fotopicaflorchico").fadeTo("fast",0.2);
    $("#fotochercan").fadeTo("fast",0.2);
    $("#fotochincol").fadeTo("fast",0.2);
    $("#fotorayaditodechiloe").fadeTo("fast",0.2);
    $("#fotodiucadechiloe").fadeTo("fast",0.2);
    $("#fototordo").fadeTo("fast",0.2);
    $("#fotocernicalo").fadeTo("fast",0.2);
    $("#fotoconcondechiloe").fadeTo("fast",0.2);
    $("#fotochoroy").fadeTo("fast",0.2);
    $("#fotopatocorrentino").fadeTo("fast",0.2);
    $("#fotomartinpescador").fadeTo("fast",0.2);
    $("#fotopilpilenaustral").fadeTo("fast",0.2);
    $("#fototucuquere").fadeTo("fast",0.2);
    $("#fotoaguilucho").fadeTo("fast",0.2);
    $("#fototaguacomun").fadeTo("fast",0.2);
    $("#fotocaranca").fadeTo("fast",0.2);
    $("#fotoquetruvolador").fadeTo("fast",0.2);
    $("#fotocormorandelasrocas").fadeTo("fast",0.2);
    $("#fotobandurria").fadeTo("fast",0.2);
    $("#fotoaguila").fadeTo("fast",0.2);
    $("#fotogarzacuca").fadeTo("fast",0.2);
    $("#fotohuala").fadeTo("fast",0.2);
  });


  $("#circulochiloe").click(function(){
    $("#fotocachudito").fadeTo("fast",0.2);
    $("#fotopicaflorchico").fadeTo("fast",0.2);
    $("#fotochercan").fadeTo("fast",0.2);
    $("#fotochincol").fadeTo("fast",0.2);
    $("#fotohuethuet").fadeTo("fast",0.2);
    $("#fototordo").fadeTo("fast",0.2);
    $("#fototorcaza").fadeTo("fast",0.2);
    $("#fotochoroy").fadeTo("fast",0.2);
    $("#fotopatocorrentino").fadeTo("fast",0.2);
    $("#fotomartinpescador").fadeTo("fast",0.2);
    $("#fotoaguilucho").fadeTo("fast",0.2);
    $("#fototucuquere").fadeTo("fast",0.2);
    $("#fotopatoreal").fadeTo("fast",0.2);
    $("#fotopeuco").fadeTo("fast",0.2);
    $("#fotocaiquen").fadeTo("fast",0.2);
    $("#fotoquetruvolador").fadeTo("fast",0.2);
    $("#fotobandurria").fadeTo("fast",0.2);
    $("#fotoaguila").fadeTo("fast",0.2);
    $("#fotohuala").fadeTo("fast",0.2);
    $("#fotocondor").fadeTo("fast",0.2);
  });

  $("#circulohornopiren").click(function(){
    $("#fotocachudito").fadeTo("fast",0.2);
    $("#fotopicaflorchico").fadeTo("fast",0.2);
    $("#fotochercan").fadeTo("fast",0.2);
    $("#fotochincol").fadeTo("fast",0.2);
    $("#fotorayaditodechiloe").fadeTo("fast",0.2);
    $("#fotodiucadechiloe").fadeTo("fast",0.2);
    $("#fotohuethuet").fadeTo("fast",0.2);
    $("#fototordo").fadeTo("fast",0.2);
    $("#fotocernicalo").fadeTo("fast",0.2);
    $("#fototorcaza").fadeTo("fast",0.2);
    $("#fotochoroy").fadeTo("fast",0.2);
    $("#fotopatocorrentino").fadeTo("fast",0.2);
    $("#fotomartinpescador").fadeTo("fast",0.2);
    $("#fotoaguilucho").fadeTo("fast",0.2);
    $("#fototucuquere").fadeTo("fast",0.2);
    $("#fotopatoreal").fadeTo("fast",0.2);
    $("#fotopeuco").fadeTo("fast",0.2);
    $("#fotocaiquen").fadeTo("fast",0.2);
    $("#fotocaranca").fadeTo("fast",0.2);
    $("#fotocormorandelasrocas").fadeTo("fast",0.2);
    $("#fotogarzacuca").fadeTo("fast",0.2);
    $("#fotobandurria").fadeTo("fast",0.2);
    $("#fotoaguila").fadeTo("fast",0.2);
    $("#fotohuala").fadeTo("fast",0.2);
  });




  
})